Repository codeit-bootcamp-frontend/2-Weekly-Mission, pull requests merged in 2023-11, with the labels that each got.

#5 [김광현] Week2
  .DS_Store
  README.md
  css/.DS_Store
  css/article.css
  css/footer.css
  css/header.css
  css/reset.css
  css/sign.css
  css/style.css
  faq.html
  images/.DS_Store
  images/akar-icons_facebook-fill.svg
  images/akar-icons_twitter-fill.svg
  images/akar-icons_youtube-fill.svg
  images/ant-design_instagram-filled.svg
  images/eye-off.svg
  images/eye-on.svg
  images/hero.png
  images/icon_google.png
  images/icon_kakao.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/logo.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#30 [김우현] Week2
  README.md
  css/basic.css
  css/footer.css
  css/header.css
  css/main.css
  css/mediaQuery.css
  css/signinup.css
  img/README.md/codeit.png
  img/card1.png
  img/card2.png
  img/card3.png
  img/card4.png
  img/headerCard.png
  img/logo.png
  img/signin/google.png
  img/signin/kakao.png
  index.html
  signin.html
  signup.html
  svg/akar-icons_facebook-fill.svg
  svg/akar-icons_twitter-fill.svg
  svg/akar-icons_youtube-fill.svg
  svg/ant-design_instagram-filled.svg
  svg/signin/eye-off.svg
  svg/signin/eye-on.svg
Labels: 매운맛🔥

#32 [이주영] week2
  faq.html
  images/edit.png
  images/facebook.svg
  images/google.png
  images/google.svg
  images/image 25.png
  images/img1.png
  images/img2.png
  images/img3.png
  images/img4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin/signin.html
  signin/style.css
  signup/signup.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#39 [윤현지]Week2
  .gitignore
  faq.html
  images/eye-off.png
  images/eye-on.png
  images/facebook.svg
  images/google.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakaotalk.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 순한맛🐏

#36 [이해빈] Week2
  assets/icon/eye-off.svg
  assets/icon/eye-on.svg
  assets/icon/facebook.svg
  assets/icon/google.png
  assets/icon/instagram.svg
  assets/icon/kakao.svg
  assets/icon/twitter.svg
  assets/icon/youtube.svg
  assets/images/edit.png
  assets/images/hero.png
  assets/images/img1.png
  assets/images/img3.png
  assets/images/search.jpg
  assets/logo/logo.svg
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  stylesheets/init/normalize.css
  stylesheets/init/reset.css
  stylesheets/main.css
  stylesheets/pages/landing.css
  stylesheets/pages/signin.css
  stylesheets/pages/signup.css
  stylesheets/theme.css
Labels: 매운맛🔥

#23 [Week2] 김동빈
  .github/delete-merged-branch-config.yml
  .github/footer/faq.html
  .github/footer/privacy.html
  .github/home.css
  .github/home.html
  .github/img/Group 20.svg
  .github/img/akar-icons_facebook-fill.svg
  .github/img/akar-icons_twitter-fill.svg
  .github/img/akar-icons_youtube-fill.svg
  .github/img/ant-design_instagram-filled.svg
  .github/img/big_logo.svg
  .github/img/eye-off.svg
  .github/img/eye-on.svg
  .github/img/file_share.png
  .github/img/folder_img.png
  .github/img/google.png
  .github/img/google_bg.svg
  .github/img/katalk.svg
  .github/img/katalk_bg.svg
  .github/img/logo.svg
  .github/img/save_img.png
  .github/img/screenshot.png
  .github/img/section1.png
  .github/member/both.css
  .github/member/signin.html
  .github/member/signup.html
  .github/pull_request_template.md
Labels: 매운맛🔥

#62 [최대성]Week2
  .gitignore
  faq.html
  images/facebook.svg
  images/hero.png
  images/ico_google.png
  images/ico_kakao.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/logo.svg
  images/signin-logo.png
  images/signup-input-active-eye-on.png
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  public/images/signup-input-active-eye-on.png
  signin.html
  signup.html
  src/reset.css
  src/singin.css
  src/singup.css
  src/style.css
Labels: 순한맛🐏

#50 Part1 김근아 week2
  .github/index.html
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin-style.css
  signin.html
  signup-style.css
  signup.html
  src/reset.css
  src/style.css
Labels: 순한맛🐏

#59 [김윤미] week2
  faq.html
  images/icon_facebook.png
  images/icon_instagram.png
  images/icon_twitter.png
  images/icon_youtube.png
  images/image_landing.png
  images/image_service1.png
  images/image_service2.png
  images/image_service3.png
  images/image_service4.png
  images/logo.svg
  images/sign/icon_eye_off.png
  images/sign/icon_eye_on.png
  images/sign/icon_google.png
  images/sign/icon_kakao.png
  images/sign/logo.svg
  index.html
  privacy.html
  signin.html
  signup.html
  styles/common.css
  styles/index.css
  styles/reset.css
  styles/sign.css
Labels: 매운맛🔥

#22 [이윤경]Week2
  faq.html
  images/download-icon.png
  images/eye-off.svg
  images/eye-on.svg
  images/footer-facebook.svg
  images/footer-instagram.svg
  images/footer-twitter.svg
  images/footer-youtube.svg
  images/google-background.svg
  images/google.png
  images/hero-image.png
  images/image1-card1.png
  images/image1-card2.png
  images/image1-card3.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/kakao-background.svg
  images/kakao.svg
  images/linkbrary-logo-sign.svg
  images/linkbrary-logo.png
  index.html
  privacy.html
  signin.html
  signup.html
  style/colors.css
  style/style-signin.css
  style/style-signup.css
  style/style.css
Labels: 매운맛🔥

#25 [남숙희] Week2
  README.md
  img/Google.png
  img/_img1.png
  img/_img4.png
  img/akar-icons_facebook-fill.png
  img/akar-icons_twitter-fill.png
  img/akar-icons_youtube-fill.png
  img/ant-design_instagram-filled.png
  img/eye-off.png
  img/image 25.png
  img/img2.png
  img/img3.png
  img/kakaotalk.png
  img/logo.png
  img/logo.svg
  index.css
  index.html
  screenshot/index1.png
  screenshot/index2.png
  screenshot/index3.png
  screenshot/index4.png
  screenshot/signin.png
  screenshot/signup.png
  sign.css
  signin.html
  signup.html
Labels: 매운맛🔥

#26 [임주민] Week2
  .gitignore
  faq.html
  images/99FE484C5C3451F218 1.svg
  images/eye-off.png
  images/eye-on.png
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/singin.css
  src/singup.css
  src/style.css
Labels: 매운맛🔥

#35 [김미진]Week2
  1-weekly-mission-week1-main/.gitignore
  1-weekly-mission-week1-main/faq.html
  1-weekly-mission-week1-main/images/facebook.svg
  1-weekly-mission-week1-main/images/hero.png
  1-weekly-mission-week1-main/images/image1.png
  1-weekly-mission-week1-main/images/image2.png
  1-weekly-mission-week1-main/images/image3.png
  1-weekly-mission-week1-main/images/image4.png
  1-weekly-mission-week1-main/images/instagram.svg
  1-weekly-mission-week1-main/images/logo.svg
  1-weekly-mission-week1-main/images/twitter.svg
  1-weekly-mission-week1-main/images/youtube.svg
  1-weekly-mission-week1-main/index.html
  1-weekly-mission-week1-main/privacy.html
  1-weekly-mission-week1-main/signin.html
  1-weekly-mission-week1-main/signup.html
  1-weekly-mission-week1-main/src/reset.css
  1-weekly-mission-week1-main/src/style.css
  css/reset.css
  css/style.css
  images/ico-eye-off.svg
  images/ico-eye-on.svg
  images/ico-google.png
  images/ico-kakao.png
  images/logo.svg
  signin.html
  signup.html
Labels: 매운맛🔥

#58 [박운성]Week2
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/icgoogle.png
  images/ickakao.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥

#38 [김주현] week2
  .gitignore
  faq.html
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakaotalk.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/main.css
  src/reset.css
  src/sign-in-up-layout.css
Labels: 매운맛🔥

#51 [Week2]김민희
  .DS_Store
  Linkbary/eye-off.png
  Linkbary/facebook.svg
  Linkbary/google.png
  Linkbary/head-img.png
  Linkbary/img1.png
  Linkbary/img2.png
  Linkbary/img3.png
  Linkbary/img4.png
  Linkbary/instagram.svg
  Linkbary/kakao.png
  Linkbary/linkbary.html
  Linkbary/logo.svg
  Linkbary/reset.css
  Linkbary/signin.html
  Linkbary/signinstyle.css
  Linkbary/signup.html
  Linkbary/signupstyle.css
  Linkbary/stylesheet.css
  Linkbary/twitter.svg
  Linkbary/youtube.svg
Labels: 매운맛🔥

#52 [이나경] Week2
  action-design.css
  color-design.css
  font-design.css
  image-design.css
  image/_img.png
  image/_img1.png
  image/_img4.png
  image/akar-icons_facebook-fill.svg
  image/akar-icons_twitter-fill.svg
  image/akar-icons_youtube-fill.svg
  image/ant-design_instagram-filled.svg
  image/card/1.png
  image/card/2.png
  image/card/3.png
  image/card/download.svg
  image/img2.png
  image/img3.png
  image/logo.svg
  image/signin/eye-off.svg
  image/social/google.png
  image/social/kakao.svg
  image/star/state=Default.svg
  index-structure.css
  index.html
  reset.css
  signin-structure.css
  signin.html
  signup.html
Labels: 매운맛🔥

#2 [정용준] week2
  .gitignore
  auth/signin.html
  auth/signup.html
  css/auth/index.css
  css/globals.css
  css/home/index.css
  css/reset.css
  index.html
Labels: 매운맛🔥

#31 [황채연]Week2
  .gitignore
  css/reset.css
  css/sign.css
  css/style.css
  faq.html
  images/facebook.svg
  images/folder.png
  images/instagram.svg
  images/introduce.png
  images/logo.svg
  images/save.png
  images/search.png
  images/share.png
  images/sign/icon/blindpassword.svg
  images/sign/icon/google.svg
  images/sign/icon/kakao.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#33 [고성선]Week2
  .github/pull_request_template.md
  images/Card.png
  images/Card1.png
  images/Group 20.svg
  images/_img 1.png
  images/_img4 1.png
  images/card-1.png
  images/eye-on.svg
  images/eye_off.svg
  images/facebook.svg
  images/google.png
  images/head_logo.svg
  images/image 25.png
  images/img 4.png
  images/img3 1.png
  images/instagram.svg
  images/kakao.png
  images/twitter.svg
  images/youtube.svg
  images/디스크립션 없는 팝업 1.png
  images/스크린샷 2023-03-17 오후 3.22 1.png
  images/폴더 공유하기 팝업 1.png
  index.html
  index.html페이지.png
  signin.css
  signin.html
  signup.css
  signup.html
  style.css
  test.txt
  로그인 페이지.png
  회원가입 페이지.png
Labels: 매운맛🔥

#34 [Week2] 박윤수
  css/fonts.css
  css/reset.css
  css/signin.css
  css/signup.css
  css/style.css
  fonts/pretendard-1.3.8/license.txt
  fonts/pretendard-1.3.8/pretendard-black.woff
  fonts/pretendard-1.3.8/pretendard-bold.woff
  fonts/pretendard-1.3.8/pretendard-extrabold.woff
  fonts/pretendard-1.3.8/pretendard-extralight.woff
  fonts/pretendard-1.3.8/pretendard-light.woff
  fonts/pretendard-1.3.8/pretendard-medium.woff
  fonts/pretendard-1.3.8/pretendard-regular.woff
  fonts/pretendard-1.3.8/pretendard-semibold.woff
  fonts/pretendard-1.3.8/pretendard-thin.woff
  imgs/card1.png
  imgs/card2.png
  imgs/card3.png
  imgs/google.png
  imgs/hero-img.png
  imgs/manage-img.png
  imgs/search-img.png
  imgs/share-img.png
  index.html
  signin/index.html
  signup/index.html
Labels: 매운맛🔥

#45 [박지선] Week2
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakaotalk.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥

#37 [Week2] 권부근
  .gitignore
  auth/signin.html
  auth/signup.html
  auth/styles.css
  faq.html
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  src/reset.css
  src/style.css
Labels: 매운맛🔥

#97 [김성연] Week3
  .github/delete-merged-branch-config.yml
  .github/pull_request_template.md
  .gitignore
  .vscode/settings.json
  css/common.css
  css/landing.css
  css/reset.css
  css/signin.css
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#93 [우준석]Week3
  .gitignore
  images/library.jpeg
  index.html
  signin/signin-style.css
  signin/signin.html
  signup/signup-style.css
  signup/signup.html
  src/style.css
Labels: bug, 매운맛🔥, 미완성

#84 [허우림]Week3
  css/index.css
  css/signin-up.css
  images/eye-off.png
  images/eye-on.png
  images/google-icon.png
  images/kakao-icon.png
  images/logo.png
  images/section2.png
  images/section3.png
  images/section4.png
  images/section5.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥, 미완성

#96 [정성원]Week3
  index.html
  signin.html
  signup.html
  src/landingstyle.css
  src/signstyle.css
Labels: 매운맛🔥

#82 [유미정] Week3
  css/global_styles.css
  css/index.css
  css/reset.css
  css/sign.css
  img/icon/eye_off_icon.svg
  img/icon/eye_on_icon.svg
  img/icon/sns_icon_facebook.svg
  img/icon/sns_icon_instagram.svg
  img/icon/sns_icon_sign_google.png
  img/icon/sns_icon_sign_kakao.png
  img/icon/sns_icon_twitter.svg
  img/icon/sns_icon_youtube.svg
  img/index_preview.jpg
  img/index_section_manage.png
  img/index_section_save.png
  img/index_section_search.png
  img/index_section_share.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#98 [한지수] week3
  css/reset.css
  css/signin.css
  css/style.css
  css/variables.css
  images/Card 1.png
  images/Card-1.png
  images/Card.png
  images/facebook.png
  images/information-image1.png
  images/information-image2.png
  images/information-image3.png
  images/information-image4.png
  images/instagram.png
  images/og-image.png
  images/twitter.png
  images/youtube.png
  images/검색 팝업.png
  images/팝업이미지 배경.png
  images/폴더 공유 팝업.png
  images/폴더 관리 팝업.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#68 [임우진] week3
  images/landing-linkbrary.png
  images/section-change-folder-name.png
  images/section-codeit-search.png
  images/section-puppy-badge-card.png
  images/section-share-folder.png
  images/sign-logo.svg
  index.html
  signin.html
  signup.html
  src/index.css
  src/normalize.css
  src/reset.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥

#78 [김병화] Week3
  .gitignore
  index.html
  signin.html
  signup.html
  src/styles/normarlize.css
  src/styles/signin.css
  src/styles/signup.css
  src/styles/style.css
Labels: 매운맛🔥, 미완성

#121 [노진욱] week3
  images/eye-off.png
  images/google-bg.png
  images/google.png
  images/kakao-bg.png
  images/kakao.svg
  img/eye-off.png
  img/facebook.svg
  img/google.png
  img/hero.png
  img/instagram.svg
  img/kakao.png
  img/logo.svg
  img/og.webp
  img/sec1.png
  img/sec2.png
  img/sec3.png
  img/sec4.png
  img/signin_logo.png
  img/twitter.svg
  img/youtube.svg
  index.html
  signin.css
  signin.html
  signup.css
  signup.html
  src/reset.css
  src/style.css
Labels: 매운맛🔥

#76 [Week3] 권부근
  auth/signin.html
  auth/signup.html
  auth/styles.css
  index.html
  src/colors.css
  src/global.css
  src/reset.css
  src/style.css
Labels: 매운맛🔥

#73 [손오름] week3
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 매운맛🔥

#75 [이윤경] Week3
  .DS_Store
  images/.DS_Store
  images/image1-card1.png
  images/image1-card2.png
  images/image1-card3.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  index.html
  signin.html
  signup.html
  style/media-sign.css
  style/media.css
  style/style-sign.css
  style/style-signup.css
  style/style.css
Labels: 매운맛🔥

#104 [김주현] Week3
  faq.html
  images/Preview.jpg
  index.html
  signin.html
  signup.html
  src/color.css
  src/global.css
  src/main.css
  src/sign-in-up-layout.css
Labels: 매운맛🔥

#112 [김영은] week3
  .prettierrc
  imgs/main/home.png
  imgs/main/link-management.png
  imgs/main/link-management01.png
  imgs/main/link-search.png
  imgs/main/link-search01.png
  imgs/main/link-share01.png
  imgs/main/link-share02.png
  imgs/main/save_link01.png
  imgs/main/save_link_card1.png
  imgs/main/save_link_card2.png
  imgs/main/save_link_card2_1.png
  imgs/main/save_link_card3.png
  imgs/main/save_link_ico_save.svg
  imgs/main/section04_01.png
  imgs/sign/sign_google.png
  imgs/sign/sign_kakao.png
  index.html
  sign.css
  signin.html
  signup.html
  src/reset.css
  src/sign.css
  src/style.css
  style.css
Labels: 매운맛🔥

#123 [박운성] Week3
  images/meta_image.png
  images/sign/eye-off.svg
  images/sign/google.png
  images/sign/icgoogle.png
  images/sign/ickakao.png
  images/sign/kakao.png
  index.html
  signin.html
  signup.html
  src/index-media.css
  src/sign-media.css
  src/style.css
Labels: 매운맛🔥

#70 [김광현] week3
  .github/.gitignore
  README.md
  css/article.css
  css/footer.css
  css/header.css
  css/reset.css
  css/sign.css
  css/style.css
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#72 [김우현]Week3
  .gitignore
  README.md
  css/global.css
  css/main/footer.css
  css/main/header.css
  css/main/main.css
  css/mediaQuery/mediaQuery.css
  css/mediaQuery/mediaQuery_signinup.css
  css/signinup/signinup.css
  img/main/card1.png
  img/main/card2.png
  img/main/card3.png
  img/main/card4.png
  img/main/headerCard.png
  img/main/logo.png
  img/signinup/google.png
  img/signinup/kakao.png
  index.html
  signin.html
  signup.html
  svg/main/akar-icons_facebook-fill.svg
  svg/main/akar-icons_twitter-fill.svg
  svg/main/akar-icons_youtube-fill.svg
  svg/main/ant-design_instagram-filled.svg
  svg/signinup/eye-off.svg
  svg/signinup/eye-on.svg
Labels: 매운맛🔥

#81 [문필겸]Week3
  images/eye-off.png
  images/eye-on.png
  images/facebook.svg
  images/googlBack.png
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.png
  images/kakaoBack.png
  images/logo.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  img/Group 20.svg
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/folder.png
  img/header.png
  img/last.png
  img/path-to-image.png
  index.html
  signin.html
  signin_style.css
  signup.html
  signup_style.css
  src/reset.css
  src/style.css
  styles.css
Labels: 매운맛🔥

#94 [고성선] week3
  .vscode/settings.json
  images/lotto.jpg
  index.html
  signin.css
  signin.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#100 [황채연] Week3
  css/sign.css
  css/style.css
  images/og_linkbrary.webp
  index.html
Labels: 매운맛🔥

#91 [안소연] week3
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/sign-style.css
  src/style.css
Labels: 매운맛🔥

#103 [박지원-9팀]Week3
  index.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥, 미완성

#102 [정용준] week3
  auth/signin.html
  auth/signup.html
  css/auth/index.css
  css/globals.css
  css/home/index.css
  index.html
Labels: 매운맛🔥

#108 [박지선] Week3
  index.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/sign.css
Labels: 매운맛🔥

#80 [이찬주] Week3
  images/landing/cards.webp
  images/landing/folder-name-change-popup.webp
  images/landing/folder-share-popup.webp
  images/landing/main-capture.webp
  images/landing/search-capture.webp
  index.html
  signin.html
  signup.html
  styles/common.css
  styles/index.css
  styles/sign.css
Labels: 매운맛🔥

#105 [Week3] 김동빈
  .github/home.css
  .github/home.html
  .github/index.html
  .github/member/both.css
  .github/member/signin.html
  .github/member/signup.html
  .github/reset.css
  .github/style.css
Labels: 매운맛🔥

#83 [김하은] Week3
  .vscode/settings.json
  images/landing/Group_20.svg
  images/landing/admin.svg
  images/landing/main_admin.png
  images/landing/main_save1.png
  images/landing/main_save2.png
  images/landing/main_save3.png
  images/landing/main_search.png
  images/landing/main_share.png
  images/landing/save.svg
  images/landing/search.svg
  images/landing/share.svg
  images/sign/eye-off.svg
  images/sign/eye-on.svg
  images/sign/google_logo.svg
  images/sign/kakao_logo.svg
  images/sign/logo.svg
  index.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥

#122 [이채빈] Week3
  images/preview-logo.svg
  index.html
  signin.html
  signup.html
  src/signin-signup.css
  src/style.css
  src/variable.css
Labels: 매운맛🔥

#86 [박준성] Week3
  images/hero1.png
  index.html
  signin.html
  signup.html
  styles/index_style.css
  styles/reset.css
  styles/signin_signup_style.css
Labels: 순한맛🐏

#90 [박지원 - 3팀] week3
  week2/index.css
  week2/index.html
  week2/signin.css
  week2/signin.html
  week2/sigup.css
  week2/sigup.html
Labels: 매운맛🔥

#119 [이준기] Week3
  .DS_Store
  images/.DS_Store
  images/Google_icon-icons.com_66793.png
  images/eye-off.svg
  images/google.png
  images/kakao.svg
  images/카카오톡 로고 3.png
  images/컴퓨터 네트워크.jpg
  index.html
  signin.html
  signup.html
  src/.DS_Store
  src/colors.css
  src/faq.html
  src/global.css
  src/index.html
  src/landing.css
  src/privacy.html
  src/reset.css
  src/sign.css
  src/signin.html
  src/signup.html
  src/style.css
Labels: 매운맛🔥

#114 전소은]week3
  asset/change.png
  asset/landingpageimage.jpg
  css/week1.css
  css/week2-1.css
  css/week2.css
  signup.html
  week1.html
  week2-1.html
  week2.html
Labels: 매운맛🔥, 미완성

#66 [김윤수] week3
  index.html
  signin/index.html
  signup/index.html
  style.css
  week3-mobile.png
  week3-pc.png
  week3-tablet.png
Labels: 매운맛🔥

#69 [이주영] week3
  .vs/2-Weekly-Mission/FileContentIndex/f7ff509b-13bd-48aa-b97f-ac2f67f0b85d.vsidx
  .vs/2-Weekly-Mission/v17/.wsuo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  index.html
  signin/signin.html
  signin/style.css
  signup/signup.html
  signup/style.css
  style.css
Labels: 매운맛🔥

#88 [윤현지] Week3
  images/linkbrary.jpg
  index.html
  signin.html
  signup.html
  src/signin.css
  src/signup.css
  src/style.css
Labels: 순한맛🐏

#118 [Week3]김민희
  .DS_Store
  Linkbary/img-dog.png
  Linkbary/img-name.png
  Linkbary/img-search.png
  Linkbary/img-share.png
  Linkbary/linkbary.html
  Linkbary/signin.html
  Linkbary/signinstyle.css
  Linkbary/signup.html
  Linkbary/signupstyle.css
  Linkbary/stylesheet.css
Labels: 매운맛🔥, 미완성

#115 [김범승] Week3
  assets/Linkbrary.png
  assets/art.png
  assets/bed.png
  assets/building.png
  assets/car.png
  assets/dog.png
  assets/dog2.png
  assets/empty_star.png
  assets/empty_star.svg
  assets/eye-off.svg
  assets/eye-on.svg
  assets/facebook.svg
  assets/google.svg
  assets/instagram.svg
  assets/kakao.svg
  assets/light.png
  assets/magnifier.png
  assets/sunset.png
  assets/table.png
  assets/twitter.svg
  assets/youtube.svg
  css/media.css
  css/signin.css
  css/signup.css
  css/style.css
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#101 [지현기] week3
  css/color.css
  css/responsive_index.css
  css/responsive_sign.css
  css/style.css
  css/style_signin.css
  css/style_signup.css
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#124 Part1 정다희 week3
  .DS_Store
  css/reset.css
  css/style.css
  img/.DS_Store
  img/Card1.png
  img/Card2.png
  img/Card3.png
  img/check.png
  img/down.png
  img/eye-off.png
  img/facebook.png
  img/frame1.png
  img/frame2.png
  img/frame3-bg.png
  img/frame3.png
  img/frame4.png
  img/google.png
  img/i-facebook.png
  img/i-instagram.png
  img/i-twitter.png
  img/i-youtube.png
  img/kakao.png
  img/link.png
  img/login-logo.png
  img/logo.png
  img/main.jpg
  img/main.png
  img/preview.png
  img/profile.png
  img/star_off.png
  img/star_on.png
  index.html
  js/javascript.js
  signin.html
  signup.html
Labels: 매운맛🔥

#74 [김희수] Week3
  assets/images/favicon/android-chrome-192x192.png
  assets/images/favicon/android-chrome-512x512.png
  assets/images/favicon/apple-touch-icon.png
  assets/images/favicon/browserconfig.xml
  assets/images/favicon/favicon-16x16.png
  assets/images/favicon/favicon-32x32.png
  assets/images/favicon/favicon.ico
  assets/images/favicon/mstile-144x144.png
  assets/images/favicon/mstile-150x150.png
  assets/images/favicon/mstile-310x150.png
  assets/images/favicon/mstile-310x310.png
  assets/images/favicon/mstile-70x70.png
  assets/images/favicon/safari-pinned-tab.svg
  assets/images/favicon/site.webmanifest
  faq.html
  index.html
  pages/faq.html
  pages/member/signin.html
  pages/member/signup.html
  pages/privacy.html
  privacy.html
  signin.html
  signup.html
  style.css
  style.css.map
  styles/base/_global.scss
  styles/components/_footer.scss
  styles/components/_gnb.scss
  styles/constants/_breakpoint.scss
  styles/constants/_z-index.scss
  styles/layout/_grid.scss
  styles/layout/_landing-content.scss
  styles/layout/_landing-cta.scss
  styles/layout/_signin.scss
  styles/mixins/_responsive.scss
  styles/mixins/_text-style.scss
Labels: 매운맛🔥

#89 [조욱희] week3(week2와 통합제출)
  img/eye-off.png
  img/facebook.svg
  img/google.png
  img/hero.png
  img/image1.png
  img/image2.png
  img/image3.png
  img/image4.png
  img/instagram.svg
  img/kakao.png
  img/logo.svg
  img/twitter.svg
  img/youtube.svg
  index.html
  signin.html
  signup.html
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥, 미완성

#116 [week3] 김윤미
  images/image_og.png
  index.html
  styles/common.css
  styles/index.css
  styles/reset.css
  styles/sign.css
Labels: 매운맛🔥

#85 Part1 김동규
  images/main-banner-preview.png
  index.html
  signin.html
  signup.html
  src/index.css
  src/signin.css
  src/signup.css
Labels: 매운맛🔥

#131 [손오름] Week4
  common/constants.js
  common/functions.js
  common/variables.js
  folder.html
  images/eye-on.svg
  index.html
  signin.html
  signup.html
  src/signin.js
  src/signup.js
  style/colors.css
  style/global.css
  style/landing.css
  style/reset.css
  style/sign.css
Labels: 매운맛🔥

#133 [Week4] 권부근
  .github/workflows/delete-merged-branch-config.yml
  auth/main.js
  auth/signin.html
  auth/signup.html
  auth/styles.css
  auth/utill/constant.js
  auth/utill/db.js
  auth/utill/toggle.js
  auth/utill/validation.js
  folder.html
Labels: 매운맛🔥

#117 [이나경] Week3
  action-design.css
  base.css
  color-design.css
  font-design.css
  image-design.css
  image/_img.png
  image/_img1.png
  image/_img4.png
  image/card/1.png
  image/card/2.png
  image/card/3.png
  image/card/download.svg
  image/img2.png
  image/img3.png
  image/index/landing.png
  image/index/manage-folder.png
  image/index/save-link.png
  image/index/search-link.png
  image/index/share-link.png
  index-structure.css
  index.css
  index.html
  reset.css
  signin-structure.css
  signin.css
  signin.html
  signup.css
  signup.html
  utility.css
Labels: 매운맛🔥

#140 [박지원-9팀] Week4
  index.html
  signin.html
  signup.html
  src/import.js
  src/reset.css
  src/sign.css
  src/sign.js
  src/signup.js
  src/style.css
Labels: 매운맛🔥

#148 [김영은] week4
  folder.html
  js/sign.js
  signin.html
  signup.html
  src/sign.css
Labels: 미완성

#157 [허우림] Week4
  css/index.css
  css/signin-up.css
  images/facebook.png
  images/instagram.png
  images/twitter.png
  images/youtube.png
  index.html
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#132 [임우진] Week4
  .github/workflows/delete-merged-branch-config.yml
  images/eye-on.svg
  index.html
  signin.html
  signup.html
  src/css/global.css
  src/css/index.css
  src/css/reset.css
  src/css/sign.css
  src/js/common/common.js
  src/js/common/errMsg.js
  src/js/common/regex.js
  src/js/common/userInfo.js
  src/js/signin.js
  src/js/signup.js
Labels: 매운맛🔥

#142 [한지수]Week4
  css/signin.css
  css/style.css
  css/variables.css
  folder.html
  functions/signin.js
  functions/signup.js
  images/eye-on.png
  index.html
  index.js
  signin.html
  signup.html
Labels: 매운맛🔥

#153 [정성원]Week4
  folder.html
  index.html
  signin.html
  signup.html
  src/LandingStyle.css
  src/SignStyle.css
  src/common.js
  src/signin.js
  src/signup.js
Labels: 매운맛🔥, 미완성

#173 [김병화] Week4
  .gitignore
  folder.html
  images/eye-off.svg
  images/google.png
  images/kakao.svg
  index.html
  signin.html
  signup.html
  src/js/signin.js
  src/js/signup.js
  src/styles/colors.css
  src/styles/global.css
  src/styles/landing.css
  src/styles/reset.css
  src/styles/sign.css
Labels: 매운맛🔥

#159 [이윤경]Week4
  .gitignore
  folder.html
  index.html
  js/errorMessage.js
  js/functions.js
  js/regPatterns.js
  js/seletors.js
  js/signin.js
  js/signup.js
  js/userData.js
  signin.html
  signup.html
  style/media-sign.css
  style/reset.css
  style/style-sign.css
  style/style.css
Labels: 매운맛🔥, 미완성

#160 [이서영] Week4
  faq.html
  folder.html
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  js/sigin.js
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: 미완성, 순한맛🐏

#129 [안소연] week4
  folder.html
  images/eye-on.svg
  signin.html
  signup.html
  src/sign-style.css
  src/signin.js
  src/signup.js
  src/utils.js
Labels: 매운맛🔥

#106 [김현수]Week3
  .gitignore
  README.md
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
Labels: documentation, invalid

#138 [김하은] week4
  functions/error_message.js
  functions/password_visibility.js
  functions/signin_email.js
  functions/signin_password.js
  functions/signup_check.js
  functions/signup_email.js
  functions/signup_password.js
  index.html
  signin.html
  signin.js
  signin_functions.js
  signup.html
  signup.js
  signup_functions.js
  src/landing.css
  src/reset.css
  src/sign.css
  tags.js
Labels: 매운맛🔥

#145 [정용준] Week4
  auth/signin.html
  auth/signup.html
  css/auth/index.css
  css/globals.css
  src/auth/signin.js
  src/auth/signup.js
Labels: 매운맛🔥

#164 [고성선] week4
  .github/workflows/delete-merged-branch-config.yml
  folder.html
  index.html
  script/emailData.js
  script/folder.js
  script/function.js
  script/index.js
  script/signin.js
  script/signup.js
  script/tags.js
  signin.css
  signin.html
  signup.css
  signup.html
  test.txt
Labels: 매운맛🔥

#177 [박지선] Week4
  2-Weekly-Mission.code-workspace
  signin.html
  signup.html
  src/sign.css
  src/sign.js
Labels: 매운맛🔥, 미완성

#134 [김희수] week4
  assets/images/icon/eye-off.svg
  assets/images/icon/eye-on.svg
  folder.html
  script/constants.js
  script/signin.js
  script/signup.js
  script/utils.js
  signin.html
  signup.html
  style.css
  style.css.map
  styles/base/_reset.scss
  styles/components/_input-group.scss
  styles/layout/_signin.scss
Labels: 매운맛🔥

#172 Part1 정다희 week4
  .DS_Store
  css/style.css
  index.html
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#151 [김범승] Week4
  css/media.css
  css/signin.css
  css/signup.css
  css/style.css
  folder.html
  index.html
  js/index.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#139 [지현기] Week4
  css/responsive_index.css
  css/responsive_sign.css
  css/style.css
  css/style_sign.css
  folder.html
  index.html
  js/consts.js
  js/functions.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#125 [김우현] Week4
  README.md
  css/basic.css
  css/footer.css
  css/global.css
  css/header.css
  css/main.css
  css/main/main.css
  css/mediaQuery.css
  css/mediaQuery/mediaQuery.css
  css/mediaQuery/signForm.css
  css/signForm/signForm.css
  css/signinup.css
  img/card1.png
  img/card2.png
  img/card3.png
  img/card4.png
  img/headerCard.png
  img/logo.png
  index.html
  script/module/signForm/btnEvent.mjs
  script/module/signForm/iconEvent.mjs
  script/module/signForm/inputErrMsg.mjs
  script/signin.js
  script/signup.js
  signin.html
  signup.html
  svg/akar-icons_facebook-fill.svg
  svg/akar-icons_twitter-fill.svg
  svg/akar-icons_youtube-fill.svg
  svg/ant-design_instagram-filled.svg
Labels: 매운맛🔥

#128 [김광현] Week4
  .DS_Store
  .gitignore
  README.md
  css/.DS_Store
  css/header.css
  css/sign.css
  css/style.css
  images/.DS_Store
  index.html
  js/database/userData.js
  js/modules/authDOMHandler.js
  js/modules/authEventHandler.js
  js/modules/authVerifyUser.js
  js/modules/domSelectors.js
  js/modules/regexPatterns.js
  js/signUp.js
  js/signin.js
  pages/faq.html
  pages/folder.html
  pages/privacy.html
  pages/signin.html
  pages/signup.html
Labels: 매운맛🔥

#143 [이해빈] Week4
  folder.html
  js/check.js
  js/deleteError.js
  js/makeDOM.js
  js/showError.js
  js/showPassword.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
  stylesheets/pages/account.css
Labels: 매운맛🔥

#141 [윤현지] Week4
  folder.html
  index.html
  signin.html
  signin.js
  signup.html
  signup.js
  src/signin.css
  src/signup.css
Labels: 순한맛🐏

#181 [우준석]Week4
  index.html
  index.js
  signin/images/eye-off.svg
  signin/images/eye-on.svg
  signin/signin-style.css
  signin/signin.html
  signin/signin.js
  signup/images/eye-off.svg
  signup/images/eye-on.svg
  signup/signup-style.css
  signup/signup.html
  signup/signup.js
  src/reset.css
  src/style.css
Labels: 매운맛🔥, 미완성

#170 [이찬주] Week4
  data/users.js
  index.css
  index.html
  pages/faq/faq.css
  pages/faq/index.html
  pages/folder/index.html
  pages/member/sign.css
  pages/member/sign.js
  pages/member/signin/index.html
  pages/member/signin/signin.js
  pages/member/signup/index.html
  pages/member/signup/signup.js
  pages/privacy/index.html
  pages/privacy/privacy.css
  scripts/utils.js
  styles/common.css
Labels: 매운맛🔥

#180 [임우진] Week5
  folder.html
  signin.html
  signup.html
  src/css/sign.css
  src/js/common/api/signApi.js
  src/js/common/sign.js
  src/js/common/userInfo.js
  src/js/common/util/errMsg.js
  src/js/common/util/regex.js
  src/js/common/util/storage.js
  src/js/common/util/userInfo.js
  src/js/signin.js
  src/js/signup.js
Labels: 매운맛🔥

#176 [Week5] 권부근
  auth/main.js
  auth/signin.html
  auth/signup.html
  auth/utill/db.js
  auth/utill/toggle.js
  auth/utill/validation.js
  index.html
  src/js/auth/index.js
  src/js/utill/api.js
  src/js/utill/constant.js
  src/js/utill/storage.js
  src/js/utill/validation.js
  src/styles/auth/styles.css
  src/styles/common/colors.css
  src/styles/common/global.css
  src/styles/common/reset.css
  src/styles/styles.css
Labels: 매운맛🔥

#190 [한지수]Week5
  css/signin.css
  functions/signin.js
  functions/signup.js
  functions/utils.js
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#192 [김병화] Week5
  .gitignore
  signin.html
  signup.html
  src/js/signin.js
  src/js/signup.js
  src/util/constants.js
Labels: 매운맛🔥

#193 [정성원]Week5
  index.html
  signin.html
  signup.html
  src/CSS/LandingStyle.css
  src/CSS/SignStyle.css
  src/CSS/reset.css
  src/JS/commonTag.js
  src/JS/errorMsg.js
  src/JS/signin.js
  src/JS/signup.js
  src/JS/util.js
Labels: 매운맛🔥

#185 [이윤경] week5
  .DS_Store
  .gitignore
  auth/.DS_Store
  auth/js/.DS_Store
  auth/js/signin.js
  auth/js/signup.js
  auth/js/util/api.js
  auth/js/util/errorMessage.js
  auth/js/util/regPatterns.js
  auth/js/util/seletors.js
  auth/js/util/signFunctions.js
  auth/signin.html
  auth/signup.html
  auth/style/media-sign.css
  auth/style/style-sign.css
  folder.html
  index.html
  js/signin.js
  js/signup.js
  js/userData.js
  style/.DS_Store
Labels: 매운맛🔥

#184 [안소연] week5
  index.html
  privacy.html
  signin.html
  signup.html
  src/sign-service.js
  src/sign-style.css
  src/signin.js
  src/signup.js
  src/style.css
  src/utils.js
Labels: 매운맛🔥

#191 [김주현] Week5
  folder.html
  index.html
  signin.html
  signup.html
  src/function/error-components.js
  src/function/tag-selectors.js
  src/reset.css
  src/sign-in.js
  src/sign-up.js
  src/sign.css
  src/utils.js
Labels: 매운맛🔥

#165 [박지원 3팀] week4
  week2/JS/common.js
  week2/JS/signin.js
  week2/JS/sigup.js
  week2/JS/userData.js
  week2/folder.html
  week2/signin.css
  week2/signin.html
  week2/sigup.css
  week2/sigup.html
Labels: 매운맛🔥

#169 [이채빈]Week4
  folder.html
  images/visible.svg
  scripts/modules/handleErrorClass.js
  scripts/modules/toggleBtn.js
  scripts/modules/validateSignForm.js
  scripts/signin.js
  scripts/signup.js
  signin.html
  signup.html
  src/signin-signup.css
  src/variable.css
Labels: 매운맛🔥

#162 [박준성] Week4
  .DS_Store
  .vscode/settings.json
  folder.html
  index.html
  js/login.js
  js/password.js
  js/password_check.js
  js/signin_email.js
  js/signup_email.js
  signin.html
  signup.html
  styles/global.css
  styles/index.css
  styles/signin_signup.css
  styles/style.css
  styles/style2.css
Labels: 미완성

#189 [김희수] week5
  .gitignore
  folder/index.html
  package-lock.json
  package.json
  script/signin.js
  script/signup.js
  script/utils.js
  signin.html
  signup.html
  src/apis/apiCall.js
  src/constants/apis.js
  src/constants/auth.js
  src/signin.js
  src/signup.js
  src/utils/auth/api.js
  src/utils/auth/axiosInstance.js
  src/utils/auth/common.js
  src/utils/auth/errorMessage.js
  src/utils/auth/validation.js
Labels: 매운맛🔥

#208 [유미정] Week5
  js/sign_module.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#203 [김성연] week5
  js/modules/checkInput.js
  js/modules/handleEvent.js
  js/modules/request.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#205 [허우림] week5
  css/index.css
  css/signin-up.css
  js/signin.js
  js/signinValid.js
  js/signup.js
  js/signupValid.js
  signin.html
  signup.html
Labels: 매운맛🔥

#166 [이나경] Week4
  .github/workflows/delete-merged-branch-config.yml
  image/signin/eye-on.svg
  script/SignIn.js
  script/SignUtility.js
  script/Signup.js
  signin.css
  signin.html
  signup.css
  signup.html
Labels: 매운맛🔥

#215 정현진 week5
  .vscode/settings.json
  css/siginin_style.css
  css/signup_style.css
  folder.html
  js/signin.js
  signin.html
Labels: 매운맛🔥, 미완성

#211 [박지원 9팀]Week5
  signin.html
  signup.html
  src/shared.js
  src/sign.css
  src/sign.js
  src/signup.js
Labels: 매운맛🔥

#222 [김영은] week5
  folder.html
  index.html
  js/sign.js
  js/toggleEye.js
  signin.html
  signup.html
  src/sign.css
Labels: 매운맛🔥, 미완성

#224 Part1 정다희 week5 (미완성)
  .DS_Store
  .vscode/settings.json
  css/style.css
  img/eye-off.svg
Labels: 미완성

#188 [김하은] Week 5
  .vscode/settings.json
  functions/common.js
  functions/error_message.js
  functions/password_visibility.js
  functions/signin_email.js
  functions/signin_password.js
  functions/signin_verifyInput.js
  functions/signup_check.js
  functions/signup_email.js
  functions/signup_password.js
  index.html
  signin.js
  signin/index.html
  signin/signin.js
  signin/signin_functions.js
  signin_functions.js
  signup.js
  signup/index.html
  signup/signup.js
  signup/signup_functions.js
  tags.js
Labels: 매운맛🔥

#197 Part1 문필겸 week5
  JavaScript/signin.js
  images/eye-off.png
  images/eye-off.svg
  images/eye-on.png
  images/eye-on.svg
  images/googlBack.png
  images/google.png
  images/kakao.png
  images/kakao.svg
  images/kakaoBack.png
  images/logo.png
  index.html
  signin.html
  signin_style.css
  signup.html
  signup_style.css
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  src/signin.js
  src/signup.js
  src/style.css
  src/utils.js
Labels: 매운맛🔥

#204 [김재환] Week 5
  function/AddRemoveFunction.js
  function/EmailDuplicateCheck.js
  function/EmailInputFoucusoutEvent.js
  function/LoginButtonClick.js
  function/SignupButtonEvent.js
  registerUser.js
  script/function.js
  script/signin.js
  script/signup.js
  src/sign.css
Labels: 미완성, 순한맛🐏

#212 [지현기] Week5
  css/style_sign.css
  css/style_signin.css
  js/api.js
  js/consts.js
  js/functions.js
  js/signin.js
  js/signup.js
  signin.html
  signup.html
Labels: 매운맛🔥

#186 [김우현] Week5
  .github/delete-merged-branch-config.yml
  .github/pull_request_template.md
  README.md
  script/module/signForm/btnEvent.mjs
  script/module/signForm/inputValidation.mjs
  script/module/signForm/submitHandlers.mjs
  script/module/signForm/togglePasswordVisiblity.mjs
  script/signin.js
  script/signup.js
  svg/main/akar-icons_facebook-fill.svg
  svg/main/akar-icons_twitter-fill.svg
  svg/main/akar-icons_youtube-fill.svg
  svg/main/ant-design_instagram-filled.svg
  svg/signin/eye-off.svg
  svg/signin/eye-on.svg
  svg/signinup/eye-off.svg
  svg/signinup/eye-on.svg
Labels: 매운맛🔥

#200 [이해빈] Week5
  constant/constant.js
  js/check.js
  js/deleteError.js
  js/showError.js
  js/signin.js
  js/signup.js
  js/togglePasswordVisibility.js
  signin.html
  signup.html
Labels: 매운맛🔥

#206 김범승 [Week5]
  css/signin.css
  folder/index.html
  js/signin.js
  js/signup.js
  js/utils.js
  signin.html
  signup.html
Labels: 미완성

#183 [정용준] Week5
  auth/signin.html
  auth/signup.html
  css/auth/index.css
  src/auth/api.js
  src/auth/signin.js
  src/auth/signup.js
  src/commons/FetchError.js
  src/commons/Fetcher.js
  src/commons/Icon.js
  src/commons/Input.js
  src/commons/ValidationError.js
  src/commons/Validator.js
  src/constants/routes.js
Labels: 매운맛🔥

#195 [박윤수] week5
  index.html
  js/add-warning-msg.js
  js/app.js
  js/makeText.js
  js/membersList.js
  js/pwdOnOff.js
  js/return-warning-msg.js
  js/signIn.js
  js/signUp.js
  js/warning-msgs.js
  signin/index.html
  signup/index.html
Labels: 매운맛🔥

#198 [황채연] week5
  index.html
  src/email.js
  src/fetch.js
  src/password.js
  src/sign-in.js
  src/sign-up.js
Labels: 매운맛🔥

#207 고성선 [week5]
  .vscode/settings.json
  index.html페이지.png
  script/emailData.js
  script/function.js
  script/signin.js
  script/signup.js
  signin.html
  signup.html
  test.txt
  로그인 페이지.png
  회원가입 페이지.png
Labels: 매운맛🔥

#218 [박지선] Week 5
  folder.html
  signin.html
  signup.html
  src/fetch.js
  src/sign.js
Labels: 매운맛🔥, 미완성

#201 [박지원 3팀] week5
  week2/JS/sigup.js
Labels: 매운맛🔥

#163 [week4] 김윤미
  .prettierrc
  folder.html
  script/signup.js
  script/utils.js
  signin.html
  signup.html
  styles/sign.css
Labels: 매운맛🔥, 미완성

#233 [안소연] week6
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  README.md
  mock.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Hooks/useToggle.js
  src/components/Api.js
  src/components/Cards/Card.css
  src/components/Cards/Cards.js
  src/components/Cards/images/card-img.png
  src/components/Cards/images/kebab.png
  src/components/Cards/images/star.svg
  src/components/Content/Content.css
  src/components/Content/Content.js
  src/components/FolderBanner/FolderBanner.css
  src/components/FolderBanner/FolderBanner.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/facebook.svg
  src/components/Footer/instagram.svg
  src/components/Footer/twitter.svg
  src/components/Footer/youtube.svg
  src/components/Gnb/Gnb.css
  src/components/Gnb/Gnb.js
  src/components/Gnb/logo.svg
  src/components/Layout.js
  src/components/LoginButton/LoginButton.css
  src/components/LoginButton/LoginButton.js
  src/components/Profile/Profile.css
  src/components/Profile/Profile.js
  src/components/SearchBar/Search.svg
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/components/Stars/Stars.css
  src/components/Stars/Stars.js
  src/components/Stars/star-full.svg
  src/components/Stars/star.svg
  src/components/reset.css
  src/constant/API.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/formatting.js
Labels: 매운맛🔥

#234 [김하은] Week 6
  .github/delete-merged-branch-config.yml
  .vscode/settings.json
  functions/common.js
  functions/signin_verifyInput.js
  functions/signup_check.js
  functions/signup_email.js
  functions/signup_password.js
  images/landing/3.png
  images/landing/Group_20.svg
  images/landing/admin.svg
  images/landing/header.png
  images/landing/icons_facebook.svg
  images/landing/icons_instagram.svg
  images/landing/icons_twitter.svg
  images/landing/icons_youtube.svg
  images/landing/logo.svg
  images/landing/save.svg
  images/landing/search.svg
  images/landing/share.svg
  images/shared/search.svg
  images/sign/eye-off.svg
  images/sign/eye-on.svg
  images/sign/google_logo.svg
  images/sign/kakao_logo.svg
  images/sign/logo.svg
  index.html
  signin/index.html
  signin/signin.js
  signin/signin_functions.js
  signup/index.html
  signup/signup.js
  signup/signup_functions.js
  src/colors.css
  src/global.css
  src/landing.css
  src/reset.css
  src/sign.css
  tags.js
  vite-project/.eslintrc.cjs
  vite-project/.gitignore
  vite-project/README.md
  vite-project/index.html
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/api.jsx
  vite-project/src/components/App.css
  vite-project/src/components/App.jsx
  vite-project/src/components/Footer.css
  vite-project/src/components/Footer.jsx
  vite-project/src/components/FooterSocialLinks.jsx
  vite-project/src/components/Header.css
  vite-project/src/components/Header.jsx
  vite-project/src/components/Main.css
  vite-project/src/components/Main.jsx
  vite-project/src/components/MainLinkList.jsx
  vite-project/src/components/Maincard.jsx
  vite-project/src/components/Navigation.css
  vite-project/src/components/Navigation.jsx
  vite-project/src/main.jsx
  vite-project/vite.config.js
Labels: 매운맛🔥

#228 [김윤수] week6
  .github/delete-merged-branch-config.yml
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/App.js
  src/components/Card.js
  src/components/Footer.js
  src/components/Header.js
  src/components/search.js
  src/components/shared.js
  src/components/style.css
  src/img/_img.png
  src/img/eye-off.png
  src/img/eye-on.png
  src/img/google.png
  src/img/kakao.png
  src/img/logo.png
  src/img/nullimg.png
  src/img/sec1.png
  src/img/sec2.png
  src/img/sec3.png
  src/img/sec4.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 순한맛🐏

#250 [이윤경] week6
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/Components/FavoriteList.jsx
  src/Components/Footer.jsx
  src/Components/FormatTimeAgo.jsx
  src/Components/Gnb.jsx
  src/Components/Profile.jsx
  src/Components/SearchBar.jsx
  src/api.jsx
  src/asset/Search.png
  src/asset/eye-off.svg
  src/asset/eye-on.svg
  src/asset/facebook.svg
  src/asset/google-background.svg
  src/asset/google.png
  src/asset/hero-image.png
  src/asset/image1.png
  src/asset/image2.png
  src/asset/image3.png
  src/asset/image4.png
  src/asset/instagram.svg
  src/asset/kakao-background.svg
  src/asset/kakao.svg
  src/asset/linkbrary-logo-sign.svg
  src/asset/linkbrary-logo.png
  src/asset/noimage.svg
  src/asset/twitter.svg
  src/asset/youtube.svg
  src/index.css
  src/index.js
  src/index.jsx
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Globals.css
  src/styles/HomeStyles.css
Labels: 매운맛🔥

#237 [한지수] week6
  package-lock.json
  package.json
  public/favicon.ico
  public/images/codeit.png
  public/images/facebook.png
  public/images/instagram.png
  public/images/logo.png
  public/images/meatball.png
  public/images/my-profile.png
  public/images/noImage.svg
  public/images/search.png
  public/images/twitter.png
  public/images/youtube.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/component/Banner.js
  src/component/Card.js
  src/component/CardList.js
  src/component/Footer.js
  src/component/Header.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/App.module.css
  src/styles/Banner.module.css
  src/styles/Card.module.css
  src/styles/CardList.module.css
  src/styles/Footer.module.css
  src/styles/Header.module.css
Labels: 매운맛🔥

#229 [Week6] 권부근
  jsconfig.json
  public/index.html
  src/App.css
  src/App.js
  src/App.jsx
  src/App.test.js
  src/assets/icons/Search.svg
  src/assets/icons/footer/facebook.svg
  src/assets/icons/footer/index.jsx
  src/assets/icons/footer/instagram.svg
  src/assets/icons/footer/twitter.svg
  src/assets/icons/footer/youtube.svg
  src/assets/images/Avatar.png
  src/assets/images/account.png
  src/assets/images/cardImage.png
  src/assets/images/defaultImage.png
  src/assets/images/logo.svg
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/Gnb.jsx
  src/components/Profile.jsx
  src/components/common/Image/index.jsx
  src/components/common/Image/styles.css
  src/contexts/AuthContext.jsx
  src/contexts/CacheContext.jsx
  src/hooks/useDateAgo.js
  src/hooks/useFetcher.js
  src/hooks/useMutation.js
  src/index.css
  src/index.js
  src/index.jsx
  src/logo.svg
  src/pages/Folder.jsx
  src/pages/index.css
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/api.js
  src/utils/constants.js
  src/utils/storage.js
Labels: 매운맛🔥

#161 Part1 김동규 week4
  images/eye-on.svg
  signin.html
  signup.html
  src/signin.css
  src/signin.js
  src/signup.css
  src/signup.js
Labels: 매운맛🔥

#216 [이채빈] Week5
  scripts/modules/redirector.js
  scripts/modules/validateSignForm.js
  scripts/signin.js
  scripts/signup.js
  signup.html
Labels: 매운맛🔥

#258 [김미진]Week6
  .github/delete-merged-branch-config.yml
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/favorites.png
  src/assets/ico-codeit.png
  src/assets/ico-facebook.png
  src/assets/ico-instagram.png
  src/assets/ico-search.png
  src/assets/ico-twitter.png
  src/assets/ico-youtube.png
  src/assets/img-card-01.png
  src/assets/img-card-02.png
  src/assets/img-card-03.png
  src/assets/img-card-04.png
  src/assets/img-card-05.png
  src/assets/img-card-06.png
  src/assets/img-card-07.png
  src/assets/img-card-08.png
  src/assets/img-card-09.png
  src/assets/img-profile.png
  src/assets/logo.svg
  src/assets/no-img.svg
  src/components/App.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Main.css
  src/components/Main.js
  src/components/reset.css
  src/components/root.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#251 Part2 김성연 week6
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/App.tsx
  src/assets/images/icon/akar-icons_facebook-fill.svg
  src/assets/images/icon/akar-icons_twitter-fill.svg
  src/assets/images/icon/akar-icons_youtube-fill.svg
  src/assets/images/icon/ant-design_instagram-filled.svg
  src/assets/images/icon/avatar.svg
  src/assets/images/icon/logo.svg
  src/assets/images/icon/no-image.svg
  src/assets/images/icon/profile.svg
  src/assets/images/icon/search.svg
  src/components/banner/Banner.tsx
  src/components/button/SnsButton.tsx
  src/components/card/CardContainer.tsx
  src/components/card/CardItem.tsx
  src/components/input/SearchBar.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/profile/Profile.tsx
  src/custom.d.ts
  src/hooks/useRequest.ts
  src/hooks/useTimeDiff.ts
  src/index.css
  src/index.js
  src/logo.svg
  src/main.tsx
  src/pages/Shared.tsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/App.css
  src/styles/Shared.css
  src/styles/index.css
  src/styles/reset.css
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: bug, 매운맛🔥

#239 Part2 문필겸 week6
  auth/images/eye-off.svg
  auth/images/eye-on.svg
  auth/images/facebook.svg
  auth/images/google.png
  auth/images/hero.png
  auth/images/image1.png
  auth/images/image2.png
  auth/images/image3.png
  auth/images/image4.png
  auth/images/instagram.svg
  auth/images/kakao.svg
  auth/images/logo.svg
  auth/images/twitter.svg
  auth/images/youtube.svg
  auth/index.html
  auth/signin.html
  auth/signin.js
  auth/signup.html
  auth/signup.js
  auth/src/colors.css
  auth/src/global.css
  auth/src/landing.css
  auth/src/reset.css
  auth/src/sign.css
  auth/src/signin.js
  auth/src/signup.js
  auth/src/utils.js
  auth/utils.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/App.js
  src/components/Footer.js
  src/components/Main.js
  src/components/MainList.js
  src/components/SearchBar.js
  src/folderApi.js
  src/img/Search.jpg
  src/img/logo.jpg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Main.css
  src/styles/SearchBar.css
  src/styles/card.css
  src/styles/nav.css
Labels: 미완성

#259 [박지원 여] week6
  .github/delete-merged-branch-config.yml
  part2/part2_project/.eslintrc.cjs
  part2/part2_project/.gitignore
  part2/part2_project/README.md
  part2/part2_project/index.html
  part2/part2_project/package-lock.json
  part2/part2_project/package.json
  part2/part2_project/src/App.css
  part2/part2_project/src/App.jsx
  part2/part2_project/src/Components/Api.jsx
  part2/part2_project/src/Components/Footer.jsx
  part2/part2_project/src/Components/Haeder.jsx
  part2/part2_project/src/Components/Main.jsx
  part2/part2_project/src/Components/Nav.jsx
  part2/part2_project/src/Components/cardsList.jsx
  part2/part2_project/src/css/Footer.css
  part2/part2_project/src/css/Header.css
  part2/part2_project/src/css/Main.css
  part2/part2_project/src/css/Nav.css
  part2/part2_project/src/css/card.css
  part2/part2_project/src/css/index.css
  part2/part2_project/src/img/!img.svg
  part2/part2_project/src/img/Search.svg
  part2/part2_project/src/img/_img1.png
  part2/part2_project/src/img/_img4.png
  part2/part2_project/src/img/eye-off.png
  part2/part2_project/src/img/eye-on.png
  part2/part2_project/src/img/google.png
  part2/part2_project/src/img/image 25.png
  part2/part2_project/src/img/img2.png
  part2/part2_project/src/img/img3.png
  part2/part2_project/src/img/kakao.png
  part2/part2_project/src/img/logo.svg
  part2/part2_project/src/img/tittle.png
  part2/part2_project/src/index.jsx
  part2/part2_project/src/util/time.js
  part2/part2_project/vite.config.js
  week2/JS/sig_all/contants.js
  week2/JS/sig_all/utils/sig_all_func.js
  week2/JS/signin/index.js
  week2/JS/sigup/index.js
  week2/css/index.css
  week2/css/signin.css
  week2/folder/folder.html
  week2/img/_img1.png
  week2/img/_img4.png
  week2/img/eye-off.png
  week2/img/eye-on.png
  week2/img/google.png
  week2/img/image 25.png
  week2/img/img2.png
  week2/img/img3.png
  week2/img/kakao.png
  week2/img/logo.svg
  week2/img/tittle.png
  week2/index.html
  week2/signin.html
  week2/sigup.html
Labels: bug, 매운맛🔥

#266 Part2 이서영 week6
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/components/App.css
  src/components/App.js
  src/components/Card.css
  src/components/Card.jsx
  src/components/colors.css
  src/components/faq.html
  src/components/folder.html
  src/components/global.css
  src/components/images/eye-off.svg
  src/components/images/eye-on.svg
  src/components/images/facebook.svg
  src/components/images/google.png
  src/components/images/hero.png
  src/components/images/image1.png
  src/components/images/image2.png
  src/components/images/image3.png
  src/components/images/image4.png
  src/components/images/instagram.svg
  src/components/images/kakao.svg
  src/components/images/kebab.svg
  src/components/images/logo.svg
  src/components/images/shared-image-7.png
  src/components/images/star.svg
  src/components/images/twitter.svg
  src/components/images/youtube.svg
  src/components/index.html
  src/components/landing.css
  src/components/privacy.html
  src/components/reset.css
  src/components/sign.css
  src/components/signin.html
  src/components/signin.js
  src/components/signup.html
  src/components/signup.js
  src/components/utils.js
  src/index.js
Labels: 매운맛🔥, 미완성

#268 [김민희] Week6
  2-Weekly-Mission.code-workspace
  README.md
  faq.html
  folder.html
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  signin.html
  signup.html
  src/App.css
  src/App.js
  src/App.test.js
  src/colors.css
  src/components/card/card.css
  src/components/footer/Footer.js
  src/components/footer/footer.css
  src/components/navigationBar/Navbar.js
  src/components/navigationBar/nav.css
  src/global.css
  src/index.css
  src/index.js
  src/landing.css
  src/logo.svg
  src/reportWebVitals.js
  src/reset.css
  src/setupTests.js
  src/sign.css
  src/signin.js
  src/signup.js
  src/utils.js
Labels: 매운맛🔥, 미완성

#238 [손오름] Week6
  public/favicon.ico
  public/images/eye-off.svg
  public/images/eye-on.svg
  public/images/facebook.svg
  public/images/google.png
  public/images/hero.png
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/instagram.svg
  public/images/kakao.svg
  public/images/logo.svg
  public/images/no-image.png
  public/images/search.png
  public/images/twitter.svg
  public/images/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/FolderCard.js
  src/components/FolderHeader.js
  src/components/Footer.js
  src/components/Nav.js
  src/getTimeAgo.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/color.css
  src/styles/global.css
  src/styles/index.css
  src/styles/reset.css
Labels: 매운맛🔥
