Repository codeit-bootcamp-frontend/2-Weekly-Mission, pull requests merged in 2023-10, with the labels that each got.

#11 [유미정] Week2
  .vscode/settings.json
  css/global_styles.css
  css/index.css
  css/reset.css
  css/sign.css
  faq.html
  img/eye_off_icon.svg
  img/eye_on_icon.svg
  img/index_section1.png
  img/index_section2.png
  img/index_section3.png
  img/index_section4.png
  img/index_top_section.png
  img/logo.svg
  img/sns_icon_facebook.svg
  img/sns_icon_instagram.svg
  img/sns_icon_twitter.svg
  img/sns_icon_youtube.svg
  img/sns_sign_google.png
  img/sns_sign_kakao.png
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#43 [김범승] Week2
  assets/page_img1.png
  assets/page_img2.png
  assets/page_img3.png
  assets/page_img4.png
  css/reset.css
  css/signin.css
  css/signup.css
  css/style.css
  css/var.css
  faq.html
  index.html
  privacy.html
  signin.html
  signup.html
  src/Linkbrary.png
  src/art.png
  src/bed.png
  src/building.png
  src/car.png
  src/dog.png
  src/dog2.png
  src/empty_star.png
  src/empty_star.svg
  src/eye-off.svg
  src/eye-on.svg
  src/facebook.svg
  src/google.svg
  src/instagram.svg
  src/kakao.svg
  src/light.png
  src/magnifier.png
  src/sunset.png
  src/table.png
  src/twitter.svg
  src/youtube.svg
Labels: 매운맛🔥

#48 [지현기]Week2
  .github/위클리 미션 제출.code-workspace
  css/reset.css
  css/style.css
  css/style_signin.css
  css/style_signup.css
  faq.html
  img/eye-off.svg
  img/eye-on.svg
  img/facebook.svg
  img/google.svg
  img/img1.png
  img/img2.png
  img/img3.png
  img/img4.png
  img/img5.png
  img/instagram.svg
  img/kakao.svg
  img/logo.svg
  img/twitter.svg
  img/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#15 [박지원-9팀] Week2
  faq.html
  images/back-kakao.svg
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/google.png
  images/google.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥

#9 [안소연] week2
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google-back.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao-back.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/sign-style.css
  src/style.css
Labels: 매운맛🔥

#12 [Week2] 허우림
  css/index.css
  css/reset.css
  css/signin-up.css
  images/Group 20.png
  images/eye-off.png
  images/eye-on.png
  images/facebook.png
  images/google-icon.png
  images/instagram.png
  images/kakao-icon.png
  images/logo.png
  images/s2-bulldog.png
  images/s2-left.png
  images/s2-right.png
  images/sc3.png
  images/sc4.png
  images/sc5.png
  images/section1.png
  images/twitter.png
  images/white-circle.png
  images/yellow-circle.png
  images/youtube.png
  index.html
  signin.html
  signup.html
Labels: 매운맛🔥

#21 [정성원]Week2
  .github/delete-merged-branch-config.yml
  .github/pull_request_template.md
  README.md
  faq.html
  images/eye-off.png
  images/eye-on.png
  images/facebook.svg
  images/google_icon.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao_icon.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/style.css
Labels: 매운맛🔥

#13 [임우진]Week2
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/google.png
  images/googlebg.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakako.svg
  images/kakaobg.svg
  images/logo.svg
  images/sign-logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/sign.css
  src/style.css
Labels: 매운맛🔥

#27 [한지수]Week2
  css/reset.css
  css/signin.css
  css/style.css
  faq.html
  images/Card 1.png
  images/Card-1.png
  images/Card.png
  images/banner.png
  images/download.png
  images/google-icon.png
  images/kakao-icon.png
  images/login-logo.png
  images/logo.png
  images/password-icon.png
  images/검색 팝업.png
  images/유튜브.png
  images/인스타.png
  images/트위터.png
  images/팝업이미지 배경.png
  images/페이스북.png
  images/폴더 공유 팝업.png
  images/폴더 관리 팝업.png
  index.html
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#54 [김성연] Week2
  .vscode/settings.json
  css/common.css
  css/landing.css
  css/reset.css
  css/signin.css
  faq.html
  images/icon/akar-icons_facebook-fill.svg
  images/icon/akar-icons_twitter-fill.svg
  images/icon/akar-icons_youtube-fill.svg
  images/icon/ant-design_instagram-filled.svg
  images/icon/eye-on.svg
  images/icon/google.svg
  images/icon/kakao.svg
  images/icon/logo.svg
  images/landing_banner.png
  images/landing_folder.png
  images/landing_link.png
  images/landing_search.png
  images/landing_share.png
  index.html
  js/temp.js
  privacy.html
  signin.html
  signup.html
Labels: 매운맛🔥

#65 [노진욱] Week2
  .gitignore
  images/eye-off.png
  images/facebook.svg
  images/google-bg.png
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao-bg.png
  images/kakao.svg
  images/logo.svg
  images/signin_logo.png
  images/twitter.svg
  images/youtube.svg
  index.html
  signin.css
  signin.html
  signup.css
  signup.html
  src/reset.css
  src/style.css
Labels: 매운맛🔥

#44 [이준기]Week2
  faq.html
  images/Google_icon-icons.com_66793.png
  images/facebook.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  images/카카오톡 로고 3.png
  index.html
  privacy.html
  signin.html
  signup.html
  src/faq.html
  src/index.html
  src/privacy.html
  src/reset.css
  src/signin.html
  src/signup.html
  src/style.css
Labels: 매운맛🔥

#6 [김윤수] Week2
  .DS_Store
  img/_img.png
  img/eye-off.png
  img/eye-on.png
  img/google.png
  img/kakao.png
  img/logo.png
  img/sec1.png
  img/sec2.png
  img/sec3.png
  img/sec4.png
  index.html
  signin/index.html
  signup/.DS_Store
  signup/index.html
  style.css
  week2-1.png
  week2-2.png
  week2-3.png
Labels: 매운맛🔥

#53 [김병화] Week2
  .gitignore
  faq.html
  images/Group.png
  images/facebook.svg
  images/google.png
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥

#56 [성은지]Week2
  W2/Privacy.html
  W2/faq.html
  W2/img/_img1.png
  W2/img/_img4.png
  W2/img/facebook.svg
  W2/img/image 25.png
  W2/img/img2.png
  W2/img/img3.png
  W2/img/instagram.svg
  W2/img/logo.svg
  W2/img/signin/eye-off.png
  W2/img/signin/google.png
  W2/img/signin/kakaotalk.png
  W2/img/tweeter.svg
  W2/img/youtube.svg
  W2/index.html
  W2/signin.html
  W2/signup.html
  W2/src/reset.css
  W2/src/signin.css
  W2/src/singnup.css
  W2/src/style.css
Labels: 매운맛🔥, 순한맛🐏

#46 [이찬주] Week2
  .gitignore
  faq.html
  images/icons/download.svg
  images/icons/eye-off.svg
  images/icons/eye-on.svg
  images/icons/facebook-fill.svg
  images/icons/google-icon.png
  images/icons/instagram-filled.svg
  images/icons/kakao-icon.png
  images/icons/logo.svg
  images/icons/twitter-fill.svg
  images/icons/youtube-fill.svg
  images/landing/card-1.webp
  images/landing/card-2.webp
  images/landing/card-3.webp
  images/landing/folder-name-change-popup.webp
  images/landing/folder-share-popup.webp
  images/landing/main-capture.webp
  images/landing/search-capture.webp
  index.html
  privacy.html
  signin.html
  signup.html
  styles/common.css
  styles/faq.css
  styles/index.css
  styles/privacy.css
  styles/reset.css
  styles/sign.css
Labels: 매운맛🔥

#18 [김하은] Week2
  images/landing/3.png
  images/landing/Group 20.svg
  images/landing/header.png
  images/landing/icons_facebook.svg
  images/landing/icons_instagram.svg
  images/landing/icons_twitter.svg
  images/landing/icons_youtube.svg
  images/landing/logo.svg
  images/landing/main_admin.png
  images/landing/main_save1.png
  images/landing/main_save2.png
  images/landing/main_save3.png
  images/landing/main_search.png
  images/landing/main_share.png
  images/signin/eye-off.svg
  images/signin/google log.svg
  images/signin/kakao logo.svg
  images/signin/logo.svg
  images/signup/eye-on.svg
  index.html
  signin.html
  signup.html
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥

#20 [김재환]Week2
  Images/1.png
  Images/2.png
  Images/3.png
  Images/4.png
  Images/4edb32d644767d750d576d9e6c790df2.png
  Images/5.png
  Images/99FE484C5C3451F218 1.png
  Images/Ellipse 28.png
  Images/Group 20.jpg
  Images/akar-icons_facebook-fill.png
  Images/akar-icons_twitter-fill.png
  Images/akar-icons_youtube-fill.png
  Images/ant-design_instagram-filled.png
  Images/eye-off.png
  Images/facebook.png
  Images/google.png
  Images/googleimg.png
  Images/image 25.png
  Images/image423.png
  Images/logo.png
  Images/logo1.png
  Images/moresearch.png
  Images/plan-card (1).png
  Images/plan-card (2).png
  Images/plan-card (3).png
  Images/plan-card (4).png
  Images/plan-card (5).png
  Images/plan-card.png
  Images/share.png
  index.html
  palette/index.html
  palette/style.css
  signin/signin.css
  signin/signin.html
  signin/signin.js
  signup/signup.css
  signup/signup.html
  signup/signup.js
  style.css
Labels: 순한맛🐏

#24 [문필겸]Week2
  .gitignore
  img/Group 20.svg
  img/akar-icons_facebook-fill.svg
  img/akar-icons_twitter-fill.svg
  img/akar-icons_youtube-fill.svg
  img/ant-design_instagram-filled.svg
  img/eye-off.png
  img/eye-on.png
  img/folder.png
  img/googlBack.png
  img/google.png
  img/header.png
  img/kakao.png
  img/kakaoBack.png
  img/last.png
  img/logo.png
  img/logo.svg
  img/path-to-image.png
  index.html
  signin.html
  signin_style.css
  signup.html
  signup_style.css
  styles.css
Labels: 매운맛🔥

#61 [문다님] Week2
  index.html
  style.css
Labels: 미완성, 순한맛🐏

#49 [정현진] week2
  w1/index.html
  w1/logo.png
  w1/style.css
  w1/w1_img/c1.png
  w1/w1_img/c2_1.png
  w1/w1_img/c2_2.png
  w1/w1_img/c2_3.png
  w1/w1_img/c2_icon1.png
  w1/w1_img/c3.png
  w1/w1_img/c4.png
  w1/w1_img/c5.png
  w1/w1_img/f_face.png
  w1/w1_img/f_ins.png
  w1/w1_img/f_twit.png
  w1/w1_img/f_you.png
  w1/바탕 화면 - 바로 가기.lnk
  w1/사진 - 바로 가기.lnk
  w2/join.html
  w2/join_styel.css
  w2/login.html
  w2/login_styel.css
  w2/w2_img/eye-off.png
  w2/w2_img/google.bg.png
  w2/w2_img/google.png
  w2/w2_img/kakao.bg.png
  w2/w2_img/kakao.png
  w2/w2_img/logo.png
Labels: 매운맛🔥

#57 [김영은]Week2
  imgs/main/Linkbrarylogo.png
  imgs/main/footer_ico_facebook.png
  imgs/main/footer_ico_instagram.png
  imgs/main/footer_ico_twitter.png
  imgs/main/footer_ico_youtube.png
  imgs/main/section01.png
  imgs/main/section02_card 1.png
  imgs/main/section02_card 2.png
  imgs/main/section02_card 2_1.png
  imgs/main/section02_card 3.png
  imgs/main/section02_ico_save.svg
  imgs/main/section03.png
  imgs/main/section04_01.png
  imgs/main/section04_02.png
  imgs/main/section05.png
  imgs/sign/eye-off.svg
  imgs/sign/eye-on.png
  imgs/sign/google.png
  imgs/sign/kakao.png
  imgs/sign/logo.png
  index.html
  reset.css
  sign.css
  signin.html
  signup.html
  style.css
Labels: 매운맛🔥

#40 [김동규]Week2
  .gitignore
  faq.html
  images/eye-off.svg
  images/facebook.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao.png
  images/login_google.png
  images/logo.svg
  images/logologin.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/signin.css
  src/signup.css
  src/style.css
Labels: 매운맛🔥

#42 [박준성] Week2
  images/Component 2.png
  images/eye-off.svg
  images/eye-on.svg
  images/facebook.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/kakao_img-remove.png
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  signin.html
  signup.html
  styles/reset.css
  styles/style.css
  styles/style2.css
Labels: 매운맛🔥

#47 [박지원-3팀] week2
  week2/img/_img1.png
  week2/img/_img4.png
  week2/img/eye-off.png
  week2/img/eye-on.png
  week2/img/google.png
  week2/img/image 25.png
  week2/img/img2.png
  week2/img/img3.png
  week2/img/kakao.png
  week2/img/logo.svg
  week2/img/tittle.png
  week2/index.css
  week2/index.html
  week2/signin.css
  week2/signin.html
  week2/sigup.css
  week2/sigup.html
Labels: 매운맛🔥

#60 [이채빈]Week2
  .github/delete-merged-branch-config.yml
  .github/pull_request_template.md
  faq.html
  images/facebook.svg
  images/google.svg
  images/hero.png
  images/image1.png
  images/image2.png
  images/image3.png
  images/image4.png
  images/instagram.svg
  images/invisible.svg
  images/kakao.svg
  images/logo.svg
  images/twitter.svg
  images/youtube.svg
  index.html
  privacy.html
  signin.html
  signup.html
  src/reset.css
  src/signin-signup.css
  src/style.css
Labels: 매운맛🔥
