Repository codeit-bootcamp-frontend/2-Weekly-Mission, pull requests merged in 2023-12, with the labels that each got.

#243 [이준기] Week6
  .github/delete-merged-branch-config.yml
  README.md
  Time.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/Card.js
  src/Folder.css
  src/Footer.js
  src/Header.js
  src/Search.js
  src/Section.js
  src/assets/bed.png
  src/assets/brownbulldog.png
  src/assets/building.png
  src/assets/bulldog.png
  src/assets/car.png
  src/assets/chair.png
  src/assets/eye-off.svg
  src/assets/facebook.svg
  src/assets/google.png
  src/assets/hero.png
  src/assets/image1.png
  src/assets/image2.png
  src/assets/image3.png
  src/assets/image4.png
  src/assets/instagram.svg
  src/assets/kakao.svg
  src/assets/logo.svg
  src/assets/mobill.png
  src/assets/profile.svg
  src/assets/search.svg
  src/assets/twitter.svg
  src/assets/userimg.svg
  src/assets/whitelayer.png
  src/assets/youtube.svg
  src/assets/불투명.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#256 [김주현] week6
  .vscode/settings.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/facebook.svg
  src/assets/instagram.svg
  src/assets/kebab.svg
  src/assets/logo.svg
  src/assets/no-img-logo.svg
  src/assets/search.svg
  src/assets/state=Default.svg
  src/assets/state=Selected.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/CardList.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Navbar.js
  src/components/SearchBar.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/services/api.js
  src/setupTests.js
  src/styles/color.css
  src/styles/global.css
  src/styles/index.css
  src/styles/reset.css
Labels: 매운맛🔥

#264 [박준성] Week6
  .github/delete-merged-branch-config.yml
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/facebook.svg
  src/assets/instagram.svg
  src/assets/logo.svg
  src/assets/search.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/App.js
  src/components/Card.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/Style.css
  src/components/Title.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성

#277 [이해빈] Week7
  package-lock.json
  package.json
  postcss.config.js
  src/App.js
  src/assets/add.svg
  src/assets/delete.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/whiteAdd.svg
  src/components/AddLinkForm.js
  src/components/Card.js
  src/components/Folder.js
  src/components/FolderLayout.js
  src/components/FolderLists.js
  src/components/FolderOwner.js
  src/components/FolderTitle.js
  src/components/Footer.js
  src/components/Nav.js
  src/components/NoLink.js
  src/components/Page/FolderPage.js
  src/components/Page/SharedPage.js
  src/components/SelectMenu.js
  src/components/Test.js
  src/components/util/dateDiff.js
  src/constants/constants.js
  src/hooks/folderPageHooks.js
  src/hooks/sharedPageHooks.js
  src/index.js
  src/styles/AddLinkForm.css
  src/styles/Card.css
  src/styles/FolderLists.css
  src/styles/FolderTitle.css
  src/styles/Nav.css
  src/styles/NoLink.css
  src/styles/SelectMenu.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 매운맛🔥

#283 [황채연] week7
  .pnp.cjs
  package.json
  src/App.css
  src/components/AddLink.jsx
  src/components/AddLink.module.css
  src/components/AddLinkHeader.jsx
  src/components/AddLinkHeader.module.css
  src/components/Card.css
  src/components/Card.jsx
  src/components/EditFeatures.jsx
  src/components/EditFeatures.module.css
  src/components/EmptyCardList.css
  src/components/EmptyCardList.jsx
  src/components/FolderButtons.jsx
  src/components/FolderButtons.module.css
  src/components/FolderCardList.jsx
  src/components/FolderCardList.module.css
  src/components/Navbar.jsx
  src/components/Navbar.module.css
  src/components/Profile.jsx
  src/components/SearchBar.jsx
  src/components/SearchBar.module.css
  src/components/SignButton.css
  src/hooks/useGetData.jsx
  src/images/add.svg
  src/images/kebab.svg
  src/images/pen.svg
  src/images/share.svg
  src/images/star.svg
  src/images/trash.svg
  src/index.css
  src/index.js
  src/pages/Folder.jsx
  src/pages/Folder.module.css
  src/pages/Router.jsx
  src/pages/Shared.jsx
  yarn.lock
Labels: 매운맛🔥

#275 [권부근] Week7
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/icons/add.svg
  src/assets/icons/folder/delete.svg
  src/assets/icons/folder/index.jsx
  src/assets/icons/folder/pen.svg
  src/assets/icons/folder/share.svg
  src/assets/icons/footer/index.jsx
  src/assets/icons/kebab.svg
  src/assets/icons/link.svg
  src/assets/icons/star.svg
  src/assets/styles/GlobalStyles.jsx
  src/assets/styles/PageInfo/index.jsx
  src/assets/styles/card/index.jsx
  src/assets/styles/cta/index.jsx
  src/assets/styles/folder/index.jsx
  src/assets/styles/footer/index.jsx
  src/assets/styles/gnb/index.jsx
  src/assets/styles/tag/index.jsx
  src/assets/styles/theme.js
  src/components/Card.jsx
  src/components/CardList.jsx
  src/components/Fab.jsx
  src/components/FolderInfo.jsx
  src/components/Footer.jsx
  src/components/Gnb.jsx
  src/components/Layout.jsx
  src/components/PageForm.jsx
  src/components/Profile.jsx
  src/components/SearchBar.jsx
  src/components/ShardInfo.jsx
  src/components/common/Image/index.jsx
  src/components/common/Image/styles.css
  src/contexts/AuthContext.jsx
  src/hooks/useFetcher.js
  src/index.css
  src/index.jsx
  src/pages/Folder.jsx
  src/pages/Shared.jsx
  src/pages/index.css
  src/router.jsx
  src/utils/api.js
  src/utils/constants.js
  src/utils/storage.js
Labels: 매운맛🔥

#276 [김윤수] week7
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/components/App.js
  src/components/Card.js
  src/components/Choice.js
  src/components/Folder.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Style.js
  src/components/style.css
  src/hooks/useFolder.js
  src/img/delete.png
  src/img/kebab.png
  src/img/link.png
  src/img/nullimg.png
  src/img/pen.png
  src/img/share.png
  src/img/star.png
  src/index.js
  src/utils/useAgo.js
  src/utils/useformatDate.js
Labels: 매운맛🔥

#279 [손오름] Week7
  package-lock.json
  package.json
  public/images/add.png
  public/images/floating-add.png
  public/images/kebab.png
  public/images/link-add-btn.png
  public/images/link.png
  public/images/pen.png
  public/images/remove.png
  public/images/share.png
  public/images/star.png
  src/App.js
  src/Main.js
  src/api.js
  src/components/AddLink.css
  src/components/AddLink.js
  src/components/App.js
  src/components/FloatingAddBtn.css
  src/components/FloatingAddBtn.js
  src/components/FolderBody.css
  src/components/FolderBody.js
  src/components/FolderCard.css
  src/components/FolderCard.js
  src/components/FolderHeader.js
  src/components/FolderHeader.module.css
  src/components/FolderHeaderUtils.css
  src/components/FolderHeaderUtils.js
  src/components/FolderSortingTab.css
  src/components/FolderSortingTab.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Nav.css
  src/components/Nav.js
  src/components/SearchLink.css
  src/components/SearchLink.js
  src/components/SelectedFolderRender.js
  src/components/SharedBody.css
  src/components/SharedBody.js
  src/components/SharedFolderCard.css
  src/components/SharedFolderCard.js
  src/components/SharedHeader.css
  src/components/SharedHeader.js
  src/getTimeAgo.js
  src/index.js
  src/pages/Folder.css
  src/pages/Forder.js
  src/pages/Shared.js
  src/styles/index.css
Labels: 매운맛🔥

#287 [문필겸] Week6
  package-lock.json
  package.json
  src/api.js
  src/components/App.js
  src/components/FolderList.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/MainList.js
  src/components/Nav.js
  src/folderApi.js
  src/footer/footer.js
  src/img/akar-icons_facebook-fill.png
  src/img/akar-icons_twitter-fill.png
  src/img/akar-icons_youtube-fill.png
  src/img/ant-design_instagram-filled.png
  src/img/logo.svg
  src/index.js
  src/styles/Main.css
  src/styles/SearchBar.css
  src/styles/card.css
  src/styles/footer.css
  src/styles/nav.css
Labels: 매운맛🔥, 미완성

#302 [정현진] week6
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/assets/Search.svg
  src/assets/akar-icons_facebook-fill.png
  src/assets/akar-icons_twitter-fill.png
  src/assets/akar-icons_youtube-fill.png
  src/assets/alt-image.svg
  src/assets/ant-design_instagram-filled.png
  src/assets/logo.svg
  src/assets/myprofile.svg
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/Nav.js
  src/css/Footer.css
  src/css/Header.css
  src/css/Main.css
  src/css/Nav.css
  src/css/style.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥

#272 [김광현] week7
  README.md
  package-lock.json
  package.json
  src/App.js
  src/assets/add.svg
  src/assets/addwhite.svg
  src/assets/kebab.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/assets/star.svg
  src/assets/trash.svg
  src/components/CardList/CardList.css
  src/components/CardList/CardList.js
  src/components/CardList/CardList.jsx
  src/components/FolderInfo/FolderInfo.jsx
  src/components/Footer/Footer.js
  src/components/Footer/Footer.jsx
  src/components/NavBar/NavBar.jsx
  src/components/atoms/Cta/Cta.jsx
  src/components/atoms/FolderList/FolderList.jsx
  src/components/atoms/FolderList/FolderList.module.css
  src/components/atoms/FolderTitle/FolderTitle.jsx
  src/components/atoms/FolderTitle/FolderTitle.module.css
  src/components/atoms/LinkInput/LinkInput.css
  src/components/atoms/LinkInput/LinkInput.jsx
  src/components/atoms/SearchBar/SearchBar.css
  src/components/atoms/SearchBar/SearchBar.jsx
  src/components/atoms/UserInfo/UserInfo.jsx
  src/list-mock.json
  src/pages/FolderPage/FolderPage.jsx
  src/pages/FolderPage/FolderPage.module.css
  src/pages/Layout.jsx
  src/pages/SharedPage/SharedPage.css
  src/pages/SharedPage/SharedPage.jsx
  src/utils/api.js
Labels: 매운맛🔥

#307 [김우현] Week7
  README.md
  package-lock.json
  package.json
  src/App.js
  src/GlobalStyles.js
  src/api/dataTransform.js
  src/api/getShareCardData.js
  src/api/getUserData.js
  src/api/getUserPersoanlLinkData.js
  src/api/getUserPersonalFolderData.js
  src/component/Card.js
  src/component/CardList.js
  src/component/Footer.js
  src/component/HeaderFolderSection.js
  src/component/HeaderSearchSection.js
  src/component/LinkNotFound.js
  src/component/LinkSearchInput.js
  src/component/MainContainer.js
  src/component/Navbar.js
  src/component/NotFoundPage.js
  src/component/TestLanding.js
  src/component/UserPersonalFolder.js
  src/component/UserPersonalFolderList.js
  src/component/UserPersonalFolderSideBar.js
  src/component/shared/footer/Footer.css
  src/component/shared/footer/Footer.js
  src/component/shared/header/Header.css
  src/component/shared/header/Header.js
  src/component/shared/header/HeaderFolderSection.js
  src/component/shared/header/Navbar.js
  src/component/shared/main/Card.js
  src/component/shared/main/Main.css
  src/component/shared/main/Main.js
  src/img/akar-icons_facebook-fill.svg
  src/img/akar-icons_twitter-fill.svg
  src/img/akar-icons_youtube-fill.svg
  src/img/ant-design_instagram-filled.svg
  src/img/codeit-favicon.png
  src/img/codeit.png
  src/img/delete.svg
  src/img/kebab.svg
  src/img/link.svg
  src/img/logo.png
  src/img/pen.svg
  src/img/share.svg
  src/img/star.svg
  src/index.js
  src/pages/Folder.js
  src/pages/Shared.js
  src/utils/date.js
  src/utils/fetchData.js
Labels: 매운맛🔥

#303 [김하은] Week7
  .gitignore
  .vscode/settings.json
  images/folder/add.svg
  images/folder/add_white.svg
  images/folder/bin.svg
  images/folder/kebab.svg
  images/folder/link.svg
  images/folder/pen.svg
  images/folder/share.svg
  images/folder/star.svg
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/api.jsx
  vite-project/src/components/App.css
  vite-project/src/components/App.jsx
  vite-project/src/components/FolderHeader.jsx
  vite-project/src/components/FolderMain.jsx
  vite-project/src/components/FolderMainCard.jsx
  vite-project/src/components/FolderMainCards.jsx
  vite-project/src/components/Footer.css
  vite-project/src/components/Footer.jsx
  vite-project/src/components/Header.css
  vite-project/src/components/Header.jsx
  vite-project/src/components/Main.css
  vite-project/src/components/Maincard.jsx
  vite-project/src/components/Navigation.css
  vite-project/src/components/Navigation.jsx
  vite-project/src/components/SharedHeader.jsx
  vite-project/src/components/SharedMain.jsx
  vite-project/src/components/SharedMainCard.jsx
  vite-project/src/components/styled.jsx
  vite-project/src/hooks/useAsync.jsx
  vite-project/src/main.jsx
  vite-project/src/pages/FolderPage.jsx
  vite-project/src/pages/SharedPage.jsx
  vite-project/src/pages/TempPage.jsx
Labels: 매운맛🔥

#306 [김성연] week7
  .eslintrc.json
  package.json
  src/App.tsx
  src/assets/images/icon/add-white.svg
  src/assets/images/icon/add.svg
  src/assets/images/icon/delete.svg
  src/assets/images/icon/kebab.svg
  src/assets/images/icon/link.svg
  src/assets/images/icon/pen.svg
  src/assets/images/icon/share.svg
  src/assets/images/icon/star-selected.svg
  src/assets/images/icon/star.svg
  src/components/banner/Banner.tsx
  src/components/banner/FolderBanner.module.css
  src/components/banner/FolderBanner.tsx
  src/components/banner/SharedBanner.module.css
  src/components/banner/SharedBanner.tsx
  src/components/button/FolderButton.module.css
  src/components/button/FolderButton.tsx
  src/components/button/GradientButton.module.css
  src/components/button/GradientButton.tsx
  src/components/button/GrayIconButton.module.css
  src/components/button/GrayIconButton.tsx
  src/components/button/SnsButton.module.css
  src/components/button/SnsButton.tsx
  src/components/card/CardContainer.module.css
  src/components/card/CardItem.module.css
  src/components/card/CardItem.tsx
  src/components/card/FolderCardContainer.tsx
  src/components/card/SharedCardContainer.tsx
  src/components/input/AddLinkBar.module.css
  src/components/input/AddLinkBar.tsx
  src/components/input/SearchBar.module.css
  src/components/input/SearchBar.tsx
  src/components/layout/Footer.module.css
  src/components/layout/Footer.tsx
  src/components/layout/Header.module.css
  src/components/layout/Header.tsx
  src/components/profile/Profile.module.css
  src/components/profile/Profile.tsx
  src/contexts/AuthContexts.tsx
  src/hooks/useAsync.ts
  src/hooks/useTimeDiff.ts
  src/index.css
  src/main.tsx
  src/pages/Folder.module.css
  src/pages/Folder.tsx
  src/pages/Shared.module.css
  src/pages/Shared.tsx
  src/reset.css
  src/styles/App.css
  src/styles/Shared.css
  src/utils/api.ts
  src/utils/getTimeDiff.ts
  yarn.lock
Labels: bug, 매운맛🔥

#294 [김재환]Week7
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/asset/add.svg
  src/asset/delete.svg
  src/asset/kebab.svg
  src/asset/link.svg
  src/asset/pen.svg
  src/asset/share.svg
  src/asset/star.svg
  src/component/App.js
  src/component/FolderCard.js
  src/component/FolderHeader.js
  src/component/FolderMain.js
  src/component/Footer.js
  src/component/InfoLoader.js
  src/component/Nav.js
  src/component/SharedCard.js
  src/component/SharedHeader.js
  src/component/SharedMain.js
  src/component/UserFolderList.js
  src/css/card.css
  src/css/footer.css
  src/css/headerfolder.css
  src/css/headershared.css
  src/css/index.css
  src/css/main.css
  src/css/nav.css
  src/css/userFolderList.css
  src/index.js
  src/pages/FolderPage.js
  src/pages/SharedPage.js
Labels: 미완성, 순한맛🐏

#305 [이채빈] Week6
  package-lock.json
  package.json
  public/images/facebook.svg
  public/images/google.svg
  public/images/hero.png
  public/images/image1.png
  public/images/image2.png
  public/images/image3.png
  public/images/image4.png
  public/images/instagram.svg
  public/images/invisible.svg
  public/images/kakao.svg
  public/images/logo.svg
  public/images/no-image.png
  public/images/preview-logo.svg
  public/images/search.svg
  public/images/twitter.svg
  public/images/visible.svg
  public/images/youtube.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  src/components/App.js
  src/components/atoms/Cta.js
  src/components/atoms/Logo.js
  src/components/atoms/SearchBar.js
  src/components/atoms/SnsBadges.js
  src/components/atoms/UserBadge.js
  src/components/molecules/Card/index.js
  src/components/molecules/Card/style.js
  src/components/molecules/Footer/index.js
  src/components/molecules/Footer/style.js
  src/components/molecules/Gnb/index.js
  src/components/molecules/Gnb/style.js
  src/components/molecules/SharedFolderTitle/index.js
  src/components/molecules/SharedFolderTitle/style.js
  src/components/template/Shared/Header/index.js
  src/components/template/Shared/Header/style.js
  src/components/template/Shared/Main/index.js
  src/components/template/Shared/Main/style.js
  src/components/template/Shared/index.js
  src/hooks/useFetch.js
  src/index.js
  src/pages/SharedPage.js
  src/styles/global.js
  src/styles/variables.css
  src/utils/formatISOdate.js
  src/utils/getElapsedTime.js
Labels: 매운맛🔥

#270 [허우림] week7
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/Search.svg
  src/assets/add.svg
  src/assets/card/kebab.svg
  src/assets/card_no-img.svg
  src/assets/footer/facebook.png
  src/assets/footer/instagram.png
  src/assets/footer/twitter.png
  src/assets/footer/youtube.png
  src/assets/link.svg
  src/assets/logo.png
  src/assets/option/pen.svg
  src/assets/option/share.svg
  src/assets/option/star.svg
  src/assets/option/trash-can.svg
  src/components/App.js
  src/components/api/api.js
  src/components/error/NoLinks.css
  src/components/error/NoLinks.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/footer/Sns.js
  src/components/header/AddLink.css
  src/components/header/AddLink.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/header/LoginButton.js
  src/components/header/Logo.js
  src/components/main/Card.css
  src/components/main/Card.js
  src/components/main/CardInfo.js
  src/components/main/CardWrapper.js
  src/components/main/FolderOptions.js
  src/components/main/Folders.js
  src/components/main/Main.css
  src/components/main/MainHeader.js
  src/components/main/Option.js
  src/components/main/Responsive.css
  src/components/main/SearchBar.css
  src/components/main/SearchBar.js
  src/components/pages/ErrorPage.js
  src/components/pages/FolderPage.js
  src/components/pages/SharedPage.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 매운맛🔥, 미완성

#146 [김윤수] week4
  .github/workflows/delete-merged-branch-config.yml
  index.html
  js/sign.js
  js/sign_let.js
  js/signin.js
  js/signin_func.js
  js/signup.js
  js/signup_func.js
  js/signup_let.js
  signin/index.html
  signup/index.html
  style.css
  week4-signin.png
  week4-signup.png
Labels: 매운맛🔥
