Repository codeit-bootcamp-frontend/2-Weekly-Mission, pull requests merged in 2024-01, with the labels that each got.

#321 [유미정] Week11
  package-lock.json
  package.json
  src/assets/icon/icon-close-search.svg
  src/components/SearchBar/SearchBar.jsx
  src/components/common/Card/Card.jsx
  src/components/common/ModalInput/ModalInput.module.css
  src/pages/FolderPage.jsx
  src/pages/SharedPage.jsx
  src/util/useSearchLink.js
Labels: 매운맛🔥, 미완성

#324 [이서영] week11
  README.md
  package-lock.json
  public/images/cancel.svg
  screenshots/folderPage.png
  screenshots/folderPage2.png
  screenshots/folderPage3.png
  src/components/Card.css
  src/components/Card.jsx
  src/components/images/kebab.svg
  src/global.css
  src/index.js
  src/page-layout/FolderPage/FolderPage.jsx
  src/page-layout/SharedPage/SharedPage.jsx
  src/reset.css
  src/ui/SearchBar/SearchBar.css
  src/ui/SearchBar/SearchBar.jsx
  src/ui/SearchBar/constant.js
  yarn.lock
Labels: 매운맛🔥, 미완성

#329 [김윤수] week11
  .eslintrc.js
  .github/delete-merged-branch-config.yml
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/GlobalStyle.tsx
  src/Main.js
  src/Main.tsx
  src/api.js
  src/api.tsx
  src/components/App.js
  src/components/Card.js
  src/components/Card/index.tsx
  src/components/Card/styled.tsx
  src/components/Choice/index.tsx
  src/components/Choice/styled.tsx
  src/components/Favor/index.tsx
  src/components/Favor/styled.tsx
  src/components/Folder.js
  src/components/Footer/index.tsx
  src/components/Footer/styled.tsx
  src/components/Header.js
  src/components/Header/index.tsx
  src/components/Header/styled.tsx
  src/components/Search/index.tsx
  src/components/Search/styled.tsx
  src/components/modal/index.tsx
  src/components/modal/styled.tsx
  src/components/search.js
  src/components/shared.js
  src/components/style.css
  src/hooks/useFolder.js
  src/hooks/useFolder.tsx
  src/hooks/useTargetRef.tsx
  src/img/facebook.png
  src/img/sharemodal.png
  src/index.js
  src/index.tsx
  src/pages/Folder/index.tsx
  src/pages/Folder/styled.tsx
  src/pages/Shared/index.tsx
  src/pages/Shared/styled.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/utils/formatDateYMD.js
  src/utils/sortAgo.js
  tsconfig.json
Labels: 매운맛🔥, 미완성

#320 [김성연] week 8 + 11
  src/App.tsx
  src/assets/images/icon/close.svg
  src/assets/images/icon/facebook.svg
  src/assets/images/icon/kakao.svg
  src/assets/images/icon/link-share.svg
  src/components/button/DeleteButton.module.css
  src/components/button/DeleteButton.tsx
  src/components/card/CardItem.tsx
  src/components/layout/Header.tsx
  src/components/modal/AddLinkModal.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/ModalContainer.module.css
  src/components/modal/ModalContainer.tsx
  src/components/modal/ModalContents.module.css
  src/components/modal/ShareModal.tsx
  src/contexts/AuthContexts.tsx
  src/hooks/useAsync.ts
  src/pages/Folder.tsx
  src/pages/Shared.tsx
  src/pages/constant.ts
Labels: 매운맛🔥, 미완성

#340 [김희수] Week8, 11
  index.html
  package-lock.json
  package.json
  src/apis/SWR/App.jsx
  src/apis/SWR/FolderProvider.jsx
  src/apis/SWR/fetcher.js
  src/components/common/Button.jsx
  src/components/common/Dialog.jsx
  src/components/common/Filter.jsx
  src/components/common/FilterOptions.jsx
  src/components/common/Input.jsx
  src/components/common/Modal.jsx
  src/components/common/Overlay.jsx
  src/components/common/Search.jsx
  src/components/common/Skeleton.jsx
  src/components/folder/AddLinkForm.jsx
  src/components/folder/CardItem.jsx
  src/components/folder/Filter.jsx
  src/components/folder/FilterContent.jsx
  src/components/folder/FilterOptions.jsx
  src/components/folder/FolderList.jsx
  src/components/folder/GridLayout.jsx
  src/components/folder/MainBanner.jsx
  src/components/folder/MainContent.jsx
  src/components/folder/Search.jsx
  src/components/folder/ShareLink.jsx
  src/components/layout/Header.jsx
  src/components/linkFolder/AddLinkForm.jsx
  src/components/linkFolder/CardItem.jsx
  src/components/linkFolder/FilterContent.jsx
  src/components/shareLink/GridLayout.jsx
  src/pages/Folder.jsx
  src/pages/Home.jsx
  src/store/common.js
  src/styles/components/_add-link.scss
  src/styles/components/_cardItem.scss
  src/styles/components/_filter.scss
  src/styles/components/_folder-list.scss
  src/styles/components/_input-group.scss
  src/styles/components/_modal.scss
  src/styles/components/_search-bar.scss
  src/styles/components/_share-list.scss
  src/styles/layout/_folder.scss
  src/styles/layout/_overlay.scss
  src/styles/main.css
  src/styles/main.scss
  src/styles/modules/_button.scss
  src/utils/onClickOutside.js
  src/utils/shareKakaoLink.js
  src/utils/useAsync.js
  tsconfig.json
  vite-env.d.ts
  vite.config.js
Labels: 미완성

#339 [이찬주] Week8, 11
  .pnp.cjs
  .pnp.loader.mjs
  .prettierrc.mjs
  .yarnrc.yml
  index.html
  package.json
  public/images/icons/Kakao.svg
  public/images/icons/check.svg
  public/images/icons/close.svg
  src/App.jsx
  src/App.tsx
  src/components/Account/index.jsx
  src/components/Card/Card.module.css
  src/components/Card/index.jsx
  src/components/CardList/index.jsx
  src/components/SearchBar/SearchBar.module.css
  src/components/SearchBar/index.jsx
  src/components/SearchBar/index.tsx
  src/components/layout/Gnb.jsx
  src/components/modal/CommonModal.jsx
  src/components/modal/CommonModal.module.css
  src/components/modal/Modal.module.css
  src/components/modal/Modal.tsx
  src/contexts/LayoutContext.tsx
  src/contexts/ModalContext.tsx
  src/contexts/UserContext.tsx
  src/hooks/useIntersect.ts
  src/main.js
  src/main.tsx
  src/pages/folder/FolderHeader.jsx
  src/pages/folder/FolderHeader.module.css
  src/pages/folder/FolderMain.jsx
  src/pages/folder/FolderMain.module.css
  src/pages/folder/FolderMain.tsx
  src/pages/folder/FolderPage.jsx
  src/pages/folder/FolderPage.tsx
  src/pages/folder/api.ts
  src/pages/landing/LandingPage.tsx
  src/pages/shared/SharedHeader.jsx
  src/pages/shared/SharedPage.jsx
  src/pages/shared/SharedPage.tsx
  src/pages/shared/api.ts
  src/scripts/fetchApi.ts
  src/types/folder.ts
  src/types/shared.ts
  src/types/user.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  yarn.lock
Labels: 매운맛🔥, 미완성

#319 [황채연] week 8 & 11
  src/components/AddLink.jsx
  src/components/AddLinkHeader.jsx
  src/components/AddLinkHeader.module.css
  src/components/AddToFolderModal.jsx
  src/components/AddToFolderModal.module.css
  src/components/CTA.css
  src/components/CTA.jsx
  src/components/Card.css
  src/components/Card.jsx
  src/components/Dropdown.jsx
  src/components/Dropdown.module.css
  src/components/EditFeatures.jsx
  src/components/EditFeatures.module.css
  src/components/FolderButtons.jsx
  src/components/FolderButtons.module.css
  src/components/FolderCardList.jsx
  src/components/Footer.jsx
  src/components/ModalLayout.jsx
  src/components/ModalLayout.module.css
  src/components/Navbar.jsx
  src/components/SearchBar.jsx
  src/components/SearchBar.module.css
  src/components/SignButton.jsx
  src/images/check.svg
  src/images/close.svg
  src/pages/Folder.jsx
Labels: 매운맛🔥, 미완성

#331 [임주민] week7,8
  vite-project/index.html
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/App.jsx
  vite-project/src/assets/Group 36.svg
  vite-project/src/assets/add.svg
  vite-project/src/assets/check.svg
  vite-project/src/assets/close.svg
  vite-project/src/assets/kebab.svg
  vite-project/src/assets/link.svg
  vite-project/src/assets/no-image.svg
  vite-project/src/assets/pen.svg
  vite-project/src/assets/share.svg
  vite-project/src/assets/star.svg
  vite-project/src/components/AddLink.jsx
  vite-project/src/components/CardList.jsx
  vite-project/src/components/CardListFolderMenu.jsx
  vite-project/src/components/CardListTitleMenu.jsx
  vite-project/src/components/FolderPageCardList.jsx
  vite-project/src/components/Header.jsx
  vite-project/src/components/Modal/AddFolderMenuModal.jsx
  vite-project/src/components/Modal/AddLinkModal.jsx
  vite-project/src/components/Modal/DeleteFolderMenuModal.jsx
  vite-project/src/components/Modal/KebabModal.jsx
  vite-project/src/components/Modal/RenameFolderMenuModal.jsx
  vite-project/src/components/Modal/ShareFolderMenuModal.jsx
  vite-project/src/components/Nav.jsx
  vite-project/src/components/SearchBar.jsx
  vite-project/src/constants/constant.jsx
  vite-project/src/main.jsx
  vite-project/src/pages/FolderPage.jsx
  vite-project/src/pages/SharedPage.jsx
  vite-project/src/style/AddFolderMenuModal.css
  vite-project/src/style/AddLink.css
  vite-project/src/style/AddLinkModal.css
  vite-project/src/style/CardList.css
  vite-project/src/style/CardListFolderMenu.css
  vite-project/src/style/CardListTitleMenu.css
  vite-project/src/style/DeleteFolderMenuModal.css
  vite-project/src/style/KebabModal.css
  vite-project/src/style/Nav.css
  vite-project/src/style/RenameFolderMenuModal.css
  vite-project/src/utils/time.jsx
  vite-project/src/utils/transCardLinkData.jsx
Labels: 미완성

#338 [손오름] Week8
  public/images/Facebook.png
  public/images/Kakao.png
  public/images/check.png
  public/images/modal_close.png
  public/index.html
  src/App.js
  src/api.js
  src/common/Modal/LayoutSns.jsx
  src/common/Modal/Modal.jsx
  src/common/Modal/Modal.module.css
  src/components/AddLink.js
  src/components/App.js
  src/components/FloatingAddBtn.css
  src/components/FloatingAddBtn.js
  src/components/FolderBody.js
  src/components/FolderCard.js
  src/components/FolderContents.js
  src/components/FolderHeader.js
  src/components/FolderHeaderUtils.js
  src/components/FolderLinkCard.css
  src/components/FolderLinkCard.js
  src/components/FolderSortingTab.js
  src/components/FolderTabs.css
  src/components/FolderTabs.js
  src/components/KebabMenu.js
  src/components/LinkSearchInput .js
  src/components/LinkSearchInput.css
  src/components/Nav.css
  src/components/Nav.js
  src/components/SelectedFolderRender.js
  src/components/hooks/useAsync.js
  src/index.js
  src/pages/Folder.css
  src/pages/MainLayout.js
  src/pages/Shared.js
  src/utills/formatDate.js
Labels: 미완성

#299 [임우진] Week7
  package-lock.json
  package.json
  public/images/card-kebab.svg
  public/images/card-star.svg
  public/images/folder-delete.svg
  public/images/folder-link.svg
  public/images/folder-pen.svg
  public/images/folder-share.svg
  src/Main.js
  src/api/codeit.js
  src/index.js
  src/molecules/Card/Card.css
  src/molecules/CardContent/CardContent.jsx
  src/molecules/CardList/CardList.jsx
  src/molecules/CardReadOnly/ReadOnlyCard.jsx
  src/molecules/FolderAddLink/FolderAddLink.jsx
  src/molecules/FolderAddLink/index.js
  src/molecules/FolderFeature/FolderFeature.css
  src/molecules/FolderFeature/FolderFeature.jsx
  src/molecules/FolderFeature/constatns.js
  src/molecules/FolderFeature/index.js
  src/molecules/FolderKebab/FolderKebab.css
  src/molecules/FolderKebab/FolderKebab.jsx
  src/molecules/FolderKebab/constants.js
  src/molecules/FolderKebab/index.js
  src/molecules/FolderNavClick/FolderNavClick.css
  src/molecules/FolderNavClick/FolderNavClick.jsx
  src/molecules/FolderNavClick/index.js
  src/molecules/FolderNavList/FolderNavList.css
  src/molecules/FolderNavList/FolderNavList.jsx
  src/molecules/FolderNavList/index.js
  src/molecules/FolderStar/FolderStar.css
  src/molecules/FolderStar/FolderStar.jsx
  src/molecules/FolderStar/constants.js
  src/molecules/FolderStar/index.js
  src/molecules/LinkAddBar/LinkAddBar.css
  src/molecules/LinkAddBar/LinkAddBar.jsx
  src/molecules/LinkAddBar/constant.js
  src/molecules/LinkAddBar/index.js
  src/molecules/Profile/Profile.jsx
  src/organisms/Main/FolderPage/FolderPage.css
  src/organisms/Main/FolderPage/FolderPage.jsx
  src/organisms/Main/FolderPage/index.js
  src/pages/folder.js
  src/pages/shared.js
  src/style/Cta/BaseLink.js
  src/style/reset.css
  src/templates/Layout.jsx
Labels: 미완성

#313 Part2 문필겸 week7
  package-lock.json
  package.json
  src/api.js
  src/components/App.js
  src/components/FolderList.js
  src/components/MainList.js
  src/folderPage/FolderHeader.js
  src/folderPage/FolderList/FolderListChange/FolderAll.js
  src/folderPage/FolderList/FolderListChange/FolderAllCss.js
  src/folderPage/FolderList/FolderListChange/FolderListAll.js
  src/folderPage/FolderList/FolderListMenu.js
  src/folderPage/FolderList/ListCss.js
  src/folderPage/FolderNav.js
  src/folderPage/FolderPage.js
  src/folderPage/HearderCss.js
  src/img/add.png
  src/img/kebab.png
  src/img/link.png
  src/img/star.png
  src/index.js
  src/styles/Main.css
  src/styles/SearchBar.css
Labels: 미완성

#342 [김하은] Week8
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/App.jsx
  vite-project/src/api.jsx
  vite-project/src/api/api.js
  vite-project/src/assets/close.svg
  vite-project/src/assets/facebook.svg
  vite-project/src/assets/kakao.svg
  vite-project/src/assets/linkcopy.svg
  vite-project/src/components/App.jsx
  vite-project/src/components/FolderHeader.jsx
  vite-project/src/components/FolderMain.jsx
  vite-project/src/components/FolderMainCard.jsx
  vite-project/src/components/FolderMainCards.jsx
  vite-project/src/components/Footer.jsx
  vite-project/src/components/FooterSocialLinks.jsx
  vite-project/src/components/Navigation.jsx
  vite-project/src/components/SharedHeader.jsx
  vite-project/src/components/SharedMain.jsx
  vite-project/src/components/SharedMainCard.jsx
  vite-project/src/components/common/Button.jsx
  vite-project/src/components/common/FolderList.jsx
  vite-project/src/components/common/Footer.jsx
  vite-project/src/components/common/Input.jsx
  vite-project/src/components/common/Layout.jsx
  vite-project/src/components/common/Modal.jsx
  vite-project/src/components/common/Navigation.jsx
  vite-project/src/components/common/Overlay.jsx
  vite-project/src/components/common/ShareLink.jsx
  vite-project/src/components/styled.jsx
  vite-project/src/hooks/useAsync.jsx
  vite-project/src/main.jsx
  vite-project/src/pages/FolderPage.jsx
  vite-project/src/pages/SharedPage.jsx
  vite-project/src/stores/constants.js
  vite-project/src/stores/dataInitialType.js
  vite-project/src/styles/Main.jsx
  vite-project/src/styles/global.jsx
  vite-project/src/utils/getDateInfo.js
  vite-project/src/utils/mapFolderData.js
  vite-project/src/utils/mapLinksData.js
Labels: 매운맛🔥, 미완성

#370 [박준성] Week12
  components/elements/Card.jsx
  components/elements/EmailInput.jsx
  components/elements/Footer.jsx
  components/elements/Header.jsx
  components/elements/Input.module.css
  components/elements/Kebab.jsx
  components/elements/PasswordInput.jsx
  components/elements/Search.jsx
  components/elements/SubmitButton.jsx
  components/folderPage/AddLink.jsx
  components/folderPage/FolderList.jsx
  components/folderPage/FolderListButton.jsx
  components/sharedPage/UserProfile.jsx
  components/signinPage/LogoTitle.jsx
  lib/axios.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/_app.tsx
  pages/_document.jsx
  pages/_document.tsx
  pages/folder.jsx
  pages/index.jsx
  pages/index.tsx
  pages/shared.jsx
  pages/signin.jsx
  pages/signup.jsx
  public/addList.svg
  public/close.svg
  public/delete.svg
  public/edit.svg
  public/eye-off.svg
  public/eye-on.svg
  public/facebook.svg
  public/favicon.ico
  public/instagram.svg
  public/kebab.svg
  public/link.svg
  public/logo.svg
  public/next.svg
  public/none.svg
  public/search.svg
  public/share.svg
  public/star.svg
  public/twitter.svg
  public/vercel.svg
  public/youtube.svg
  styles/Home.module.css
  styles/Signin.module.css
  styles/globals.css
  utils/time.js
Labels: 미완성

#357 [김윤수] week12
  .eslintrc.js
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  components/Card/index.tsx
  components/Card/styled.tsx
  components/Choice/index.tsx
  components/Choice/styled.tsx
  components/Favor/index.tsx
  components/Favor/styled.tsx
  components/Footer/index.tsx
  components/Footer/styled.tsx
  components/Header/index.tsx
  components/Header/styled.tsx
  components/Search/index.tsx
  components/Search/styled.tsx
  components/modal/index.tsx
  components/modal/styled.tsx
  components/style.css
  hooks/useFolder.tsx
  hooks/useTargetRef.tsx
  lib/axios.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/folder/[id].tsx
  pages/folder/styled.tsx
  pages/index.tsx
  pages/shared/[id].tsx
  pages/shared/styled.tsx
  pages/signin.tsx
  pages/signup.tsx
  pages/signup/styled.tsx
  public/img/_img.png
  public/img/delete.png
  public/img/eye-off.png
  public/img/eye-on.png
  public/img/facebook.png
  public/img/google.png
  public/img/kakao.png
  public/img/kebab.png
  public/img/link.png
  public/img/logo.png
  public/img/nullimg.png
  public/img/pen.png
  public/img/sec1.png
  public/img/sec2.png
  public/img/sec3.png
  public/img/sec4.png
  public/img/share.png
  public/img/sharemodal.png
  public/img/star.png
  styles/SignUp.module.css
  styles/globals.css
  utils/formatDateYMD.js
  utils/sortAgo.js
Labels: 매운맛🔥, 미완성

#273 [박준성] Week7
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/assets/delete.svg
  src/assets/editimg.svg
  src/assets/kebab.svg
  src/assets/link.svg
  src/assets/noneimg.svg
  src/assets/shareimg.svg
  src/assets/star.svg
  src/components/AddLink.js
  src/components/App.js
  src/components/Card-folder.js
  src/components/Card-shared.js
  src/components/Card.js
  src/components/CardInput-folder.js
  src/components/CardInput-shared.js
  src/components/FolderList.js
  src/components/Header-folder.js
  src/components/Header-shared.js
  src/components/KebabModal.js
  src/components/ListButton.js
  src/components/Main.js
  src/components/Search.js
  src/components/Style.css
  src/components/Title.js
  src/index.js
  src/pages/FolderPage.js
  src/pages/SharedPage.js
  src/time.js
Labels: 미완성

#297 [김주현] Week7
  package-lock.json
  package.json
  src/App.js
  src/Main.jsx
  src/assets/add.svg
  src/assets/delete.svg
  src/assets/link.svg
  src/assets/pen.svg
  src/assets/share.svg
  src/components/AddLink/AddLink.jsx
  src/components/App/App.jsx
  src/components/CardList.js
  src/components/CardList/CardList.css
  src/components/CardList/CardList.jsx
  src/components/ErrorMsg/NoLinksMsg.jsx
  src/components/Fab/Fab.jsx
  src/components/FolderButton/FolderButton.jsx
  src/components/FolderToobar/FolderToobar.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header.js
  src/components/Navbar.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.jsx
  src/components/SearchBar.js
  src/components/SearchBar/SearchBar.jsx
  src/data/SNS.js
  src/data/ToolUtils.js
  src/hooks/useAsync.js
  src/index.js
  src/pages/Folder/FolderPage.css
  src/pages/Folder/FolderPage.jsx
  src/pages/Shared/SharedPage.css
  src/pages/Shared/SharedPage.jsx
  src/services/api.js
  src/styles/index.css
  src/utils/date.js
Labels: 매운맛🔥

#349 [박윤수] week12
  .gitignore
  components/Card.tsx
  components/CardList.module.css
  components/CardList.tsx
  components/FolderOwner.module.css
  components/FolderOwner.tsx
  components/Header.module.css
  components/Header.tsx
  components/ProfileInfo.module.css
  components/ProfileInfo.tsx
  components/SearchBar.module.css
  components/SearchBar.tsx
  lib/axios.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/shared.tsx
  public/logo.svg
  styles/reset.css
Labels: bug, 매운맛🔥, 미완성

#375 [김윤미] week12
  .prettierrc.json
  README.md
  components/ButtonLink.module.scss
  components/ButtonLink.tsx
  components/SearchForm.module.scss
  components/SearchForm.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/folder.tsx
  pages/index.tsx
  pages/shared/[folderId].tsx
  pages/signin.tsx
  pages/signup.tsx
  public/assets/icons/search.svg
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/Home.module.scss
  styles/globals.css
  styles/globals.scss
Labels: 매운맛🔥, 미완성

#361 [김미진] week12
  package-lock.json
  package.json
  src/App.tsx
  src/components/AddFolder.tsx
  src/components/AddLinkBar.tsx
  src/components/CardList.jsx
  src/components/FolderUser.tsx
  src/components/Footer.tsx
  src/components/GlobalStyle.tsx
  src/components/JoinLink.tsx
  src/components/JoinSns.tsx
  src/components/Modal.jsx
  src/components/Nav.jsx
  src/components/Nav.tsx
  src/components/PopOver.tsx
  src/components/SignButton.jsx
  src/components/UserButton.tsx
  src/components/UserInput.jsx
  src/components/UserInput.tsx
  src/components/main/ButtonOption.tsx
  src/components/main/CardList.tsx
  src/components/main/Main.tsx
  src/components/main/MainProvider.tsx
  src/components/main/SearchBar.tsx
  src/components/main/TabMenu.tsx
  src/components/main/mainContext.ts
  src/components/modal/Modal.tsx
  src/components/modal/ModalProvider.tsx
  src/components/modal/modalContext.ts
  src/components/shareKakao.ts
  src/custom.d.ts
  src/hook/useAsync.tsx
  src/index.js
  src/index.tsx
  src/page/FolderPage.jsx
  src/page/FolderPage.tsx
  src/page/SharedPage.jsx
  src/page/SharedPage.tsx
  src/page/SigninPage.tsx
  src/page/SignupPage.tsx
  tsconfig.json
Labels: 매운맛🔥, 미완성

#381 [허우림] week13
  components/common/Card.tsx
  components/common/CardInfo.tsx
  components/common/CardWrapper.tsx
  components/common/Footer.tsx
  components/common/FooterSnsData.tsx
  components/common/Header.tsx
  components/common/LoginButton.tsx
  components/common/LoginInput.tsx
  components/common/Logo.tsx
  components/common/SearchBar.tsx
  components/common/SearchResult.tsx
  components/common/auth/AuthButton.tsx
  components/common/auth/AuthHeader.tsx
  components/common/auth/Input.tsx
  components/common/auth/SocialLogin.tsx
  components/common/auth/TextField.tsx
  components/common/folderPage/AddLink.tsx
  components/common/folderPage/Dropdown.tsx
  components/common/folderPage/FolderAddButton.tsx
  components/common/folderPage/FolderOptions.tsx
  components/common/folderPage/Option.tsx
  components/common/folderPage/modal/FolderList.tsx
  components/common/folderPage/modal/Modal.tsx
  components/common/sharedPage/MainHeader.tsx
  contexts/CardContext.jsx
  contexts/FolderContext.jsx
  contexts/KebabContext.jsx
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/assets/icons/auth/eye-off.svg
  public/assets/icons/auth/eye-on.svg
  public/assets/icons/auth/google.svg
  public/assets/icons/auth/kakaotalk.svg
  public/assets/icons/header/logo.png
  public/assets/icons/header/logo.svg
  public/assets/icons/search/Search-active.svg
  public/assets/icons/search/Search-inactive.svg
  public/assets/icons/search/close.svg
  styles/auth/auth.module.css
  styles/auth/authButton.module.css
  styles/auth/socialLogin.module.css
  styles/card/cardWrapper.module.css
  styles/folderPage/addLink.module.css
  styles/globals.css
  styles/search/searchResult.module.css
  styles/search/searchbar.module.css
  utils/api.js
  utils/api.ts
  utils/auth.ts
  utils/date.ts
  utils/searchUtils.ts
  utils/validation.ts
Labels: 매운맛🔥

#389 [김광현] week13
  package-lock.json
  package.json
  page-layout/AuthLayout/AuthLayout.module.scss
  page-layout/AuthLayout/AuthLayout.tsx
  pages/signin.tsx
  pages/signup.tsx
  public/images/google.svg
  public/images/kakao.svg
  src/auth/feature-signin-form/SigninForm.module.scss
  src/auth/feature-signin-form/SigninForm.tsx
  src/auth/feature-signup-form/SignUpForm.module.scss
  src/auth/feature-signup-form/SignUpForm.tsx
  src/auth/type.ts
  src/auth/ui-header/AuthHeader.module.scss
  src/auth/ui-header/AuthHeader.tsx
  src/auth/ui-header/constant.js
  src/auth/ui-social-tool-bar/SocialToolbar.module.scss
  src/auth/ui-social-tool-bar/SocialToolbar.tsx
  src/auth/ui-social-tool-bar/constant.js
  src/auth/utils/useCheckEmail.ts
  src/auth/utils/useSignIn.ts
  src/auth/utils/useSignUp.ts
  src/auth/utils/validateEmail.ts
  src/commons/type.ts
  src/commons/ui-cta/Cta.tsx
  src/commons/ui-footer/Footer.tsx
  src/commons/ui-footer/constant.js
  src/commons/ui-input/Input.tsx
  src/commons/ui-navigation-bar/NavigationBar.tsx
  src/commons/ui-portal/Portal.tsx
  src/commons/ui-profile/Profile.tsx
  src/commons/util/useAsync.ts
  src/commons/util/useIntersectionObserver.tsx
  src/commons/util/useKakaoSdk.ts
  src/link/util/map/mapLinksData.ts
  src/link/util/useSearchLink.ts
Labels: 매운맛🔥

#400 [이윤경] Week13
  components/commons/Cta.module.css
  components/commons/Cta.tsx
  components/domains/auth/AuthInput.module.css
  components/domains/auth/AuthInput.tsx
  components/domains/auth/InputForm.module.css
  components/domains/auth/SignInForm.tsx
  components/domains/auth/SignUpForm.tsx
  components/domains/auth/commons/AuthInput.tsx
  components/domains/auth/commons/AuthLogo.module.css
  components/domains/auth/commons/AuthLogo.tsx
  components/domains/auth/commons/SNS.module.css
  components/domains/auth/commons/SNS.tsx
  components/domains/folder/FolderCardList.tsx
  components/domains/folder/FolderLists.tsx
  lib/useModal/useModal.module.css
  lib/utils/regPatterns.tsx
  lib/utils/type.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/auth.tsx
  pages/auth/signin.tsx
  pages/auth/signup.tsx
  pages/index.tsx
  styles/Home.module.css
  styles/Sign.module.css
  styles/global.css
Labels: 매운맛🔥

#404 [박준성] Week13
  components/elements/Card.jsx
  components/elements/EmailInput.jsx
  components/elements/Header.jsx
  components/elements/Input.jsx
  components/elements/PasswordInput.jsx
  components/elements/Search.jsx
  components/elements/SnsLogin.jsx
  components/elements/SubmitButton.jsx
  components/folderPage/AddLink.jsx
  components/folderPage/FolderList.jsx
  components/signPage/LogoTitle.jsx
  lib/axios.js
  lib/loginApi.js
  next.config.js
  package-lock.json
  package.json
  pages/folder.jsx
  pages/index.jsx
  pages/signin.jsx
  pages/signup.jsx
  public/googleLogo.png
  public/kakao.svg
  public/yellow.svg
  styles/Sign.module.css
  styles/Signin.module.css
  utils/regexp.js
Labels: 미완성

#388 [황채연] week13
  components/AddToFolderModal/AddToFolderModal.tsx
  components/Card/Card.tsx
  components/CardList/CardList.tsx
  components/FolderButtons/FolderButtons.tsx
  components/Loading/Loading.module.css
  components/Loading/Loading.tsx
  components/Navbar/Navbar.tsx
  components/SearchedCardList/SearchedCardList.tsx
  components/SelectedCardList/SelectedCardList.tsx
  components/SharedHeader/SharedHeader.tsx
  components/Sign/DoubleCheckPasswordInput/DoubleCheckPasswordInput.tsx
  components/Sign/EmailInput/EmailInput.tsx
  components/Sign/Input/Input.module.css
  components/Sign/Input/Input.tsx
  components/Sign/PasswordInput/PasswordInput.tsx
  components/Sign/SignInForm/SignInForm.module.css
  components/Sign/SignInForm/SignInForm.tsx
  components/Sign/SignUpForm/SignUpForm.module.css
  components/Sign/SignUpForm/SignUpForm.tsx
  components/Sign/Social/Social.module.css
  components/Sign/Social/Social.tsx
  lib/apiTypes.ts
  lib/formTypes.ts
  pages/signin.tsx
  pages/signup.tsx
  public/images/google.svg
  public/images/kakao.svg
Labels: 매운맛🔥

#394 [김미진] week13
  constant.ts
  pages/_document.tsx
  src/components/addFolder/AddFolder.tsx
  src/components/addLinkBar/AddLinkBar.tsx
  src/components/folderUser/FolderUser.tsx
  src/components/footer/Footer.tsx
  src/components/joinLink/JoinLink.tsx
  src/components/joinSns/JoinSns.tsx
  src/components/main/ButtonOption.tsx
  src/components/main/CardList.tsx
  src/components/main/MainProvider.tsx
  src/components/main/SearchBar.tsx
  src/components/main/TabMenu.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalContext.tsx
  src/components/modal/ModalProvider.tsx
  src/components/nav/Nav.tsx
  src/components/popOver/PopOver.tsx
  src/components/userButton/UserButton.tsx
  src/components/userInput/UserInput.tsx
  src/components/userInput/cooperation/UserInput.tsx
  src/hook/useAsync.tsx
Labels: 매운맛🔥

#393 [박윤수] week13
  .github/pull_request_template.md
  .github/workflows/delete-merged-branch-config.yml
  components/CardList.module.css
  components/CardListItem.tsx
  components/ErrorMessagePrint.tsx
  components/Input.tsx
  components/PwdViewChangeButton.tsx
  components/SignCheck.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/hello.ts
  pages/folder.tsx
  pages/shared.tsx
  pages/signIn.tsx
  pages/signUp.tsx
  postcss.config.js
  public/eye-off.svg
  public/eye-on.svg
  public/next.svg
  public/vercel.svg
  styles/globals.css
  tailwind.config.ts
Labels: 매운맛🔥, 미완성

#386 [안소연] week13
  package-lock.json
  public/assets/hero.png
  public/assets/image1.png
  public/assets/image2.png
  public/assets/image3.png
  public/assets/image4.png
  src/components/common/CTA.tsx
  src/components/common/FloatingActionButton.tsx
  src/components/common/FolderButton.tsx
  src/components/common/Gnb.tsx
  src/components/common/Input.tsx
  src/components/common/KebabButton.tsx
  src/components/common/Modal.tsx
  src/components/others/FolderBanner.tsx
  src/components/others/FolderEditButtons.tsx
  src/context/PageContext.tsx
  src/context/SearchContext.tsx
  src/hooks/useClickOutside.ts
  src/pages/_document.tsx
  src/pages/folder.tsx
  src/pages/index.tsx
  src/pages/shared.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/styles/index.module.css
Labels: 매운맛🔥

#407 [임우진] Week13
  components/Sign/Input.tsx
  components/Sign/InputForm.module.css
  components/Sign/InputForm.tsx
  components/Sign/Layout.tsx
  components/Sign/SignInForm.module.css
  components/Sign/SignInForm.tsx
  components/Sign/SingUpForm.module.css
  components/Sign/SingUpForm.tsx
  components/Sign/passwordInput.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/shared/index.tsx
  pages/signIn/index.tsx
  pages/signUp/index.tsx
Labels: 미완성

#399 [정용준] Week13
  bun.lockb
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  src/apis/auth/auth.schema.ts
  src/apis/auth/auth.ts
  src/apis/fetcher.ts
  src/apis/user/user.schema.ts
  src/apis/user/user.ts
  src/components/auth/SigninForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/SocialSigninNav.tsx
  src/components/auth/SocialSignupNav.tsx
  src/components/common/Footer.tsx
  src/components/common/GNB.tsx
  src/components/common/Input.tsx
  src/components/common/SearchBar.tsx
  src/components/common/icon/Icon.tsx
  src/components/folder/HeroHeader.tsx
  src/components/landing/HeroHeader.tsx
  src/components/shared/FolderOwner.tsx
  src/providers/AuthProvider.tsx
  src/resolvers/auth.resolver.ts
  src/resolvers/user.resolver.ts
  src/routes.ts
  src/styles/globals.css
  src/utils/auth.ts
  src/utils/regex.ts
Labels: 매운맛🔥

#403 [김윤미] week13
  components/Button.module.scss
  components/Button.tsx
  components/Container.module.scss
  components/Container.tsx
  components/Input.module.scss
  components/Input.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/signup.tsx
  public/assets/icons/eye-off.svg
  public/assets/icons/eye-on.svg
  public/assets/images/google.png
  public/assets/images/kakao.png
  public/assets/images/logo.svg
  styles/Home.module.scss
  styles/SignupPage.module.scss
  styles/colors.scss
  styles/globals.scss
  styles/mixin.scss
  styles/reset.scss
Labels: 매운맛🔥, 미완성

#406 [이해빈] Week13
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/folder/index.tsx
  pages/shared/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  src/assets/eye-off.svg
  src/assets/eye-on.svg
  src/assets/google.png
  src/assets/kakaoLogin.svg
  src/common/Components/CardSection/CardSection.module.css
  src/common/Components/CardSection/CardSection.tsx
  src/common/Components/Footer/Footer.tsx
  src/common/Components/LinkCard/LinkCard.tsx
  src/common/Components/LinkCard/SelectMenu.tsx
  src/common/Components/Nav/Nav.tsx
  src/common/Components/SearchBar/SearchBar.tsx
  src/folder/Components/AddLinkForm.module.css
  src/folder/Components/AddLinkForm.tsx
  src/folder/Components/FolderLists.module.css
  src/folder/Components/FolderLists.tsx
  src/folder/Components/FolderPage.tsx
  src/folder/Components/FolderTitle.tsx
  src/folder/Components/NoLink.tsx
  src/home/Components/Test.tsx
  src/modal/Components/AddModal.tsx
  src/modal/Components/EditModal.tsx
  src/modal/Components/ShareModal.tsx
  src/shared/Components/FolderOwner.tsx
  src/shared/Components/SharedPage.tsx
  src/sign/Components/common/EmailInput.module.css
  src/sign/Components/common/EmailInput.tsx
  src/sign/Components/common/ErrorMessage.module.css
  src/sign/Components/common/ErrorMessage.tsx
  src/sign/Components/common/EyeButton.module.css
  src/sign/Components/common/EyeButton.tsx
  src/sign/Components/common/PasswordCheckInput.tsx
  src/sign/Components/common/PasswordInput.module.css
  src/sign/Components/common/PasswordInput.tsx
  src/sign/Components/common/SignButton.module.css
  src/sign/Components/common/SignButton.tsx
  src/sign/Components/common/SignTitle.module.css
  src/sign/Components/common/SignTitle.tsx
  src/sign/Components/common/Social.module.css
  src/sign/Components/common/Social.tsx
  src/sign/Components/common/temp.module.css
  src/sign/Components/signin/SignInForm.module.css
  src/sign/Components/signin/SignInForm.tsx
  src/sign/Components/signup/SignupForm.module.css
  src/sign/Components/signup/SignupForm.tsx
  src/sign/util/validate.ts
  styles/globals.css
  tailwind.config.js
Labels: 매운맛🔥, 미완성

#423 [김민희]week14
  pages/Signin/index.tsx
  pages/shared/[id].tsx
Labels: 매운맛🔥, 미완성

#417 [이준기] week14
  .next/build-manifest.json
  .next/cache/webpack/client-development/0.pack.gz
  .next/cache/webpack/client-development/1.pack.gz
  .next/cache/webpack/client-development/2.pack.gz
  .next/cache/webpack/client-development/index.pack.gz
  .next/cache/webpack/client-development/index.pack.gz.old
  .next/cache/webpack/server-development/0.pack.gz
  .next/cache/webpack/server-development/1.pack.gz
  .next/cache/webpack/server-development/index.pack.gz
  .next/cache/webpack/server-development/index.pack.gz.old
  .next/server/middleware-build-manifest.js
  .next/server/pages-manifest.json
  .next/server/pages/_app.js
  .next/server/pages/_error.js
  .next/server/pages/index.js
  .next/server/vendor-chunks/next.js
  .next/static/chunks/pages/_app.js
  .next/static/chunks/pages/index.js
  .next/static/chunks/webpack.js
  .next/static/development/_buildManifest.js
  .next/trace
  components/FolderPage/Folder.tsx
  components/FolderPage/Header.tsx
  components/FolderPage/LogoutButton.tsx
  components/FolderPage/UserSortMenu.tsx
  components/FolderPage/hooks/useFolder.tsx
  components/FolderPage/hooks/useInput.tsx
  components/SharedPage/Card.js
  components/SharedPage/Header.js
  components/SharedPage/Search.js
  components/SharedPage/Section.js
  components/SharedPage/SharedDefault.js
  components/SigninPage/index.tsx
  components/SignupPage/index.tsx
  components/common/Icon.tsx
  components/common/input/input.tsx
  lib/axios.js
  pages/_app.tsx
  pages/folder/[[...folderId]].tsx
  pages/folder/folder.api.ts.tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared/[folderId]/index.tsx
  pages/shared/[folderId]/shared.api.ts.tsx
  pages/shared/[folderId]/type.tsx
  pages/shared/index.tsx
  pages/signin/signin.api.ts.tsx
  tsconfig.json
Labels: 매운맛🔥, 미완성

#419 [박윤수] week14
  components/CardList.tsx
  components/FolderOwner.tsx
  components/Header.tsx
  components/Input.tsx
  components/ProfileData.module.css
  components/ProfileData.tsx
  components/ProfileInfo.tsx
  next.config.js
  pages/folder.tsx
  pages/folder/[folderId].tsx
  pages/folder/index.tsx
  pages/shared.tsx
  pages/shared/[folderId].tsx
  pages/signIn.tsx
  pages/signUp.tsx
Labels: 매운맛🔥, 미완성

#424 [한지수] week14
  .eslintrc.js
  components/commons/Header.tsx
  components/domains/auth/Auth.ts
  components/domains/auth/Header.tsx
  components/domains/auth/SigninForm.tsx
  components/domains/auth/SignupForm.tsx
  components/domains/folder/FolderBadge.tsx
  components/domains/folder/FolderBadgeList.tsx
  components/domains/folder/folderTitle/FolderBadge.tsx
  components/domains/folder/folderTitle/FolderTitles.tsx
  components/domains/shared/Banner.tsx
  constants.ts
  contexts/LocaleContext.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/AuthApi.ts
  pages/api/FolderApi.ts
  pages/api/FolderApi.tsx
  pages/api/RequestApi.ts
  pages/api/SharedApi.ts
  pages/api/SharedApi.tsx
  pages/api/axios.ts
  pages/folder.tsx
  pages/folder/[folderId].tsx
  pages/folder/index.tsx
  pages/index.tsx
  pages/shared.tsx
  pages/shared/[folderId]/index.tsx
  types/common.d.ts
  utils/calculateElapsedTime.ts
  utils/convertToFormattedDate.ts
  utils/regex.ts
Labels: 매운맛🔥, 미완성

#428 [김윤미] week13
  components/ButtonLink.module.scss
  components/ButtonLink.tsx
  components/Container.module.scss
  components/SignUpForm.module.scss
  components/SignUpForm.tsx
  package-lock.json
  package.json
  pages/signup.tsx
  styles/SignupPage.module.scss
Labels: 매운맛🔥, 미완성
